/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const gridVideoHtml5Item01Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "321": 1
  },
  "barWidth": {
    "0": [
      "167px",
      "41px"
    ],
    "321": "211px"
  }
};

export const gridVideoHtml5Item01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "321": 3,
    "439": 2,
    "731": 1,
    "768": 2,
    "900": 3,
    "1110": 2
  },
  "barWidth": {
    "0": [
      "204px",
      "194px",
      "165px",
      "41px"
    ],
    "321": [
      "204px",
      "211px",
      "194px"
    ],
    "439": [
      "283px",
      "329px"
    ],
    "731": "615px",
    "768": [
      "334px",
      "278px"
    ],
    "900": [
      "224px",
      "191px",
      "194px"
    ],
    "1110": [
      "283px",
      "329px"
    ]
  }
};

export const gridVideoHtml5Item02Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "196px"
};

export const gridVideoHtml5Item02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "377": 2,
    "645": 1,
    "768": 2,
    "900": 3,
    "984": 2
  },
  "barWidth": {
    "0": [
      "162px",
      "204px",
      "159px"
    ],
    "377": [
      "263px",
      "266px"
    ],
    "645": "533px",
    "768": [
      "371px",
      "159px"
    ],
    "900": [
      "216px",
      "170px",
      "140px"
    ],
    "984": [
      "263px",
      "266px"
    ]
  }
};

export const gridVideoHtml5Item03Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "155px"
};

export const gridVideoHtml5Item03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "357": 2,
    "593": 1,
    "768": 2,
    "878": 1,
    "900": 3,
    "943": 2
  },
  "barWidth": {
    "0": [
      "182px",
      "207px",
      "86px"
    ],
    "357": [
      "247px",
      "233px"
    ],
    "593": "483px",
    "768": [
      "352px",
      "127px"
    ],
    "878": "483px",
    "900": [
      "213px",
      "210px",
      "52px"
    ],
    "943": [
      "247px",
      "233px"
    ]
  }
};

export const gridVideoHtml5Item04Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "188px"
};

export const gridVideoHtml5Item04Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "385": 2,
    "653": 1,
    "768": 2,
    "900": 3,
    "1002": 2
  },
  "barWidth": {
    "0": [
      "199px",
      "203px",
      "130px"
    ],
    "385": [
      "262px",
      "275px"
    ],
    "653": "540px",
    "768": [
      "367px",
      "170px"
    ],
    "900": [
      "199px",
      "203px",
      "130px"
    ],
    "1002": [
      "262px",
      "275px"
    ]
  }
};

export const gridVideoHtml5SkeletonText: GeneratedSkeletonTextModule = {
  gridVideoHtml5Item01Title,
  gridVideoHtml5Item01Body,
  gridVideoHtml5Item02Title,
  gridVideoHtml5Item02Body,
  gridVideoHtml5Item03Title,
  gridVideoHtml5Item03Body,
  gridVideoHtml5Item04Title,
  gridVideoHtml5Item04Body,
};
