/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const entriesGridEntry01Section: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "47px",
  "barHeight": 11.52,
  "lineHeight": 1.5
};

export const entriesGridEntry01Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "323": 1
  },
  "barWidth": {
    "0": [
      "165px",
      "39px"
    ],
    "323": "208px"
  },
  "barHeight": 17.28,
  "lineHeight": 1.2
};

export const entriesGridEntry01Count: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "53px",
  "barHeight": 12.48,
  "lineHeight": 1.5
};

export const entriesGridEntry01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "347": 3,
    "480": 2,
    "1088": 1
  },
  "barWidth": {
    "0": [
      "195px",
      "170px",
      "206px",
      "100px"
    ],
    "347": [
      "226px",
      "232px",
      "217px"
    ],
    "480": [
      "314px",
      "365px"
    ],
    "1088": "684px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65
};

export const entriesGridEntry02Section: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "44px",
  "barHeight": 11.52,
  "lineHeight": 1.5
};

export const entriesGridEntry02Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "193px",
  "barHeight": 17.28,
  "lineHeight": 1.2
};

export const entriesGridEntry02Count: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "52px",
  "barHeight": 12.48,
  "lineHeight": 1.5
};

export const entriesGridEntry02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "321": 3,
    "412": 2,
    "713": 1,
    "768": 2,
    "998": 1
  },
  "barWidth": {
    "0": [
      "179px",
      "155px",
      "166px",
      "80px"
    ],
    "321": [
      "179px",
      "207px",
      "199px"
    ],
    "412": [
      "292px",
      "297px"
    ],
    "713": "594px",
    "768": [
      "339px",
      "250px"
    ],
    "998": "594px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65
};

export const entriesGridEntry03Section: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "47px",
  "barHeight": 11.52,
  "lineHeight": 1.5
};

export const entriesGridEntry03Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "154px",
  "barHeight": 17.28,
  "lineHeight": 1.2
};

export const entriesGridEntry03Count: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "53px",
  "barHeight": 12.48,
  "lineHeight": 1.5
};

export const entriesGridEntry03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "389": 2,
    "656": 1,
    "768": 2,
    "942": 1
  },
  "barWidth": {
    "0": [
      "203px",
      "186px",
      "143px"
    ],
    "389": [
      "274px",
      "261px"
    ],
    "656": "540px",
    "768": [
      "371px",
      "165px"
    ],
    "942": "540px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65
};

export const entriesGridSkeletonText: GeneratedSkeletonTextModule = {
  entriesGridEntry01Section,
  entriesGridEntry01Title,
  entriesGridEntry01Count,
  entriesGridEntry01Body,
  entriesGridEntry02Section,
  entriesGridEntry02Title,
  entriesGridEntry02Count,
  entriesGridEntry02Body,
  entriesGridEntry03Section,
  entriesGridEntry03Title,
  entriesGridEntry03Count,
  entriesGridEntry03Body,
};
