/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const masonrySpansItem01Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem01Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "215px",
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "329": 3,
    "458": 2,
    "1057": 1,
    "1160": 2
  },
  "barWidth": {
    "0": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "329": [
      "219px",
      "225px",
      "210px"
    ],
    "458": [
      "304px",
      "354px"
    ],
    "1057": "662px",
    "1160": [
      "358px",
      "300px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansItem02Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "43px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem02Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "768": 2,
    "826": 1,
    "1160": 2
  },
  "barWidth": {
    "0": "199px",
    "768": [
      "137px",
      "58px"
    ],
    "826": "199px",
    "1160": [
      "137px",
      "58px"
    ]
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "392": 2,
    "683": 1,
    "760": 2,
    "768": 5,
    "770": 4,
    "828": 3,
    "1010": 2,
    "1160": 5,
    "1222": 4
  },
  "barWidth": {
    "0": [
      "174px",
      "200px",
      "193px"
    ],
    "392": [
      "283px",
      "288px"
    ],
    "683": "575px",
    "760": [
      "283px",
      "288px"
    ],
    "768": [
      "89px",
      "139px",
      "162px",
      "91px",
      "77px"
    ],
    "770": [
      "89px",
      "139px",
      "162px",
      "172px"
    ],
    "828": [
      "174px",
      "200px",
      "193px"
    ],
    "1010": [
      "283px",
      "288px"
    ],
    "1160": [
      "89px",
      "139px",
      "142px",
      "111px",
      "77px"
    ],
    "1222": [
      "89px",
      "139px",
      "162px",
      "172px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansItem03Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem03Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "1160": 2,
    "1176": 1
  },
  "barWidth": {
    "0": "161px",
    "1160": [
      "116px",
      "41px"
    ],
    "1176": "161px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "370": 2,
    "628": 1,
    "760": 2,
    "768": 4,
    "820": 3,
    "964": 2,
    "1160": 4,
    "1317": 3
  },
  "barWidth": {
    "0": [
      "196px",
      "180px",
      "138px"
    ],
    "370": [
      "266px",
      "253px"
    ],
    "628": "523px",
    "760": [
      "266px",
      "253px"
    ],
    "768": [
      "128px",
      "134px",
      "154px",
      "94px"
    ],
    "820": [
      "196px",
      "180px",
      "138px"
    ],
    "964": [
      "266px",
      "253px"
    ],
    "1160": [
      "128px",
      "134px",
      "154px",
      "94px"
    ],
    "1317": [
      "196px",
      "180px",
      "138px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansItem04Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "39px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem04Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "768": 2,
    "811": 1
  },
  "barWidth": {
    "0": "192px",
    "768": [
      "115px",
      "74px"
    ],
    "811": "192px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem04Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "399": 2,
    "689": 1,
    "760": 2,
    "768": 4,
    "823": 3,
    "1024": 2
  },
  "barWidth": {
    "0": [
      "214px",
      "176px",
      "182px"
    ],
    "399": [
      "282px",
      "295px"
    ],
    "689": "581px",
    "760": [
      "282px",
      "295px"
    ],
    "768": [
      "164px",
      "161px",
      "157px",
      "86px"
    ],
    "823": [
      "198px",
      "193px",
      "182px"
    ],
    "1024": [
      "282px",
      "295px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansItem05Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "29px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem05Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "192px",
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem05Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "360": 3,
    "452": 2,
    "766": 1,
    "768": 2,
    "1050": 1,
    "1160": 2
  },
  "barWidth": {
    "0": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "360": [
      "255px",
      "176px",
      "216px"
    ],
    "452": [
      "348px",
      "303px"
    ],
    "766": "655px",
    "768": [
      "348px",
      "303px"
    ],
    "1050": "655px",
    "1160": [
      "348px",
      "303px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansItem06Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "51px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem06Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "341": 1,
    "768": 2,
    "903": 1,
    "1160": 2
  },
  "barWidth": {
    "0": [
      "142px",
      "90px"
    ],
    "341": "236px",
    "768": [
      "142px",
      "90px"
    ],
    "903": "236px",
    "1160": [
      "142px",
      "90px"
    ]
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem06Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "407": 2,
    "691": 1,
    "760": 2,
    "768": 5,
    "814": 4,
    "834": 3,
    "1039": 2,
    "1160": 5,
    "1306": 4
  },
  "barWidth": {
    "0": [
      "195px",
      "177px",
      "203px"
    ],
    "407": [
      "277px",
      "302px"
    ],
    "691": "583px",
    "760": [
      "277px",
      "302px"
    ],
    "768": [
      "115px",
      "158px",
      "95px",
      "143px",
      "56px"
    ],
    "814": [
      "115px",
      "193px",
      "160px",
      "103px"
    ],
    "834": [
      "195px",
      "177px",
      "203px"
    ],
    "1039": [
      "277px",
      "302px"
    ],
    "1160": [
      "115px",
      "132px",
      "121px",
      "143px",
      "56px"
    ],
    "1306": [
      "115px",
      "193px",
      "160px",
      "103px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansItem07Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "45px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem07Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "768": 2,
    "850": 1,
    "1160": 2
  },
  "barWidth": {
    "0": "211px",
    "768": [
      "100px",
      "108px"
    ],
    "850": "211px",
    "1160": [
      "100px",
      "108px"
    ]
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem07Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "449": 2,
    "721": 1,
    "760": 3,
    "768": 5,
    "771": 4,
    "837": 3,
    "1123": 2,
    "1160": 5,
    "1224": 4
  },
  "barWidth": {
    "0": [
      "204px",
      "199px",
      "200px"
    ],
    "449": [
      "263px",
      "344px"
    ],
    "721": "612px",
    "760": [
      "263px",
      "267px",
      "73px"
    ],
    "768": [
      "164px",
      "95px",
      "140px",
      "122px",
      "73px"
    ],
    "771": [
      "164px",
      "95px",
      "173px",
      "167px"
    ],
    "837": [
      "204px",
      "199px",
      "200px"
    ],
    "1123": [
      "263px",
      "344px"
    ],
    "1160": [
      "131px",
      "128px",
      "140px",
      "122px",
      "73px"
    ],
    "1224": [
      "164px",
      "95px",
      "173px",
      "167px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansItem08Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "56px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonrySpansItem08Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "347": 1,
    "768": 2,
    "915": 1
  },
  "barWidth": {
    "0": [
      "149px",
      "89px"
    ],
    "347": "242px",
    "768": [
      "149px",
      "89px"
    ],
    "915": "242px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonrySpansItem08Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "420": 2,
    "734": 1,
    "760": 3,
    "768": 4,
    "851": 3,
    "1066": 2
  },
  "barWidth": {
    "0": [
      "211px",
      "201px",
      "203px"
    ],
    "420": [
      "316px",
      "304px"
    ],
    "734": "624px",
    "760": [
      "211px",
      "237px",
      "168px"
    ],
    "768": [
      "166px",
      "146px",
      "132px",
      "168px"
    ],
    "851": [
      "211px",
      "201px",
      "203px"
    ],
    "1066": [
      "316px",
      "304px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonrySpansSkeletonText: GeneratedSkeletonTextModule = {
  masonrySpansItem01Badge,
  masonrySpansItem01Title,
  masonrySpansItem01Body,
  masonrySpansItem02Badge,
  masonrySpansItem02Title,
  masonrySpansItem02Body,
  masonrySpansItem03Badge,
  masonrySpansItem03Title,
  masonrySpansItem03Body,
  masonrySpansItem04Badge,
  masonrySpansItem04Title,
  masonrySpansItem04Body,
  masonrySpansItem05Badge,
  masonrySpansItem05Title,
  masonrySpansItem05Body,
  masonrySpansItem06Badge,
  masonrySpansItem06Title,
  masonrySpansItem06Body,
  masonrySpansItem07Badge,
  masonrySpansItem07Title,
  masonrySpansItem07Body,
  masonrySpansItem08Badge,
  masonrySpansItem08Title,
  masonrySpansItem08Body,
};
