/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const entriesSliderHtml5Entry01Section: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry01Section",
  "lines": 1,
  "barWidth": "47px",
  "barHeight": 11.52,
  "lineHeight": 1.5,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry01Title: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry01Title",
  "lines": {
    "0": 2,
    "208.296": 1
  },
  "barWidth": {
    "0": [
      "100px",
      "104px"
    ],
    "208.296": "208px"
  },
  "barHeight": 17.28,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry01Count: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry01Count",
  "lines": 1,
  "barWidth": "63px",
  "barHeight": 12.48,
  "lineHeight": 1.5,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry01Body: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry01Body",
  "lines": {
    "0": 4,
    "233": 3,
    "366": 2,
    "684": 1
  },
  "barWidth": {
    "0": [
      "195px",
      "170px",
      "206px",
      "100px"
    ],
    "233": [
      "226px",
      "232px",
      "217px"
    ],
    "366": [
      "314px",
      "365px"
    ],
    "684": "684px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry02Section: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry02Section",
  "lines": 1,
  "barWidth": "44px",
  "barHeight": 11.52,
  "lineHeight": 1.5,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry02Title: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry02Title",
  "lines": {
    "0": 2,
    "193.468": 1
  },
  "barWidth": {
    "0": [
      "83px",
      "106px"
    ],
    "193.468": "193px"
  },
  "barHeight": 17.28,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry02Count: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry02Count",
  "lines": 1,
  "barWidth": "63px",
  "barHeight": 12.48,
  "lineHeight": 1.5,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry02Body: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry02Body",
  "lines": {
    "0": 4,
    "207": 3,
    "298": 2,
    "594.093": 1
  },
  "barWidth": {
    "0": [
      "179px",
      "155px",
      "166px",
      "80px"
    ],
    "207": [
      "179px",
      "207px",
      "199px"
    ],
    "298": [
      "292px",
      "297px"
    ],
    "594.093": "594px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry03Section: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry03Section",
  "lines": 1,
  "barWidth": "47px",
  "barHeight": 11.52,
  "lineHeight": 1.5,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry03Title: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry03Title",
  "lines": {
    "0": 2,
    "154.375": 1
  },
  "barWidth": {
    "0": [
      "111px",
      "39px"
    ],
    "154.375": "154px"
  },
  "barHeight": 17.28,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry03Count: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry03Count",
  "lines": 1,
  "barWidth": "62px",
  "barHeight": 12.48,
  "lineHeight": 1.5,
  "responsiveBy": "container"
};

export const entriesSliderHtml5Entry03Body: GeneratedSkeletonTextEntry = {
  "textId": "entriesSliderHtml5Entry03Body",
  "lines": {
    "0": 3,
    "275": 2,
    "539.781": 1
  },
  "barWidth": {
    "0": [
      "203px",
      "186px",
      "143px"
    ],
    "275": [
      "274px",
      "261px"
    ],
    "539.781": "540px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65,
  "responsiveBy": "container"
};

export const entriesSliderHtml5SkeletonText: GeneratedSkeletonTextModule = {
  entriesSliderHtml5Entry01Section,
  entriesSliderHtml5Entry01Title,
  entriesSliderHtml5Entry01Count,
  entriesSliderHtml5Entry01Body,
  entriesSliderHtml5Entry02Section,
  entriesSliderHtml5Entry02Title,
  entriesSliderHtml5Entry02Count,
  entriesSliderHtml5Entry02Body,
  entriesSliderHtml5Entry03Section,
  entriesSliderHtml5Entry03Title,
  entriesSliderHtml5Entry03Count,
  entriesSliderHtml5Entry03Body,
};
