/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const entriesSliderEntry01Section: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 11.52,
  "lineHeight": 1.5
};

export const entriesSliderEntry01Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "208px",
  "barHeight": 17.28,
  "lineHeight": 1.2
};

export const entriesSliderEntry01Count: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "61px",
  "barHeight": 12.48,
  "lineHeight": 1.5
};

export const entriesSliderEntry01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "347": 3,
    "480": 2,
    "1088": 1
  },
  "barWidth": {
    "0": [
      "195px",
      "170px",
      "206px",
      "100px"
    ],
    "347": [
      "226px",
      "232px",
      "217px"
    ],
    "480": [
      "314px",
      "365px"
    ],
    "1088": "684px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65
};

export const entriesSliderEntry02Section: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "43px",
  "barHeight": 11.52,
  "lineHeight": 1.5
};

export const entriesSliderEntry02Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "193px",
  "barHeight": 17.28,
  "lineHeight": 1.2
};

export const entriesSliderEntry02Count: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "61px",
  "barHeight": 12.48,
  "lineHeight": 1.5
};

export const entriesSliderEntry02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "321": 3,
    "412": 2,
    "713": 1,
    "768": 2,
    "998": 1
  },
  "barWidth": {
    "0": [
      "179px",
      "155px",
      "166px",
      "80px"
    ],
    "321": [
      "179px",
      "207px",
      "199px"
    ],
    "412": [
      "292px",
      "297px"
    ],
    "713": "594px",
    "768": [
      "339px",
      "250px"
    ],
    "998": "594px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65
};

export const entriesSliderEntry03Section: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "45px",
  "barHeight": 11.52,
  "lineHeight": 1.5
};

export const entriesSliderEntry03Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "154px",
  "barHeight": 17.28,
  "lineHeight": 1.2
};

export const entriesSliderEntry03Count: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "62px",
  "barHeight": 12.48,
  "lineHeight": 1.5
};

export const entriesSliderEntry03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "389": 2,
    "656": 1,
    "768": 2,
    "942": 1
  },
  "barWidth": {
    "0": [
      "203px",
      "186px",
      "143px"
    ],
    "389": [
      "274px",
      "261px"
    ],
    "656": "540px",
    "768": [
      "371px",
      "165px"
    ],
    "942": "540px"
  },
  "barHeight": 15.2,
  "lineHeight": 1.65
};

export const entriesSliderSkeletonText: GeneratedSkeletonTextModule = {
  entriesSliderEntry01Section,
  entriesSliderEntry01Title,
  entriesSliderEntry01Count,
  entriesSliderEntry01Body,
  entriesSliderEntry02Section,
  entriesSliderEntry02Title,
  entriesSliderEntry02Count,
  entriesSliderEntry02Body,
  entriesSliderEntry03Section,
  entriesSliderEntry03Title,
  entriesSliderEntry03Count,
  entriesSliderEntry03Body,
};
