/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const forceOverlayHeaderTitle: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayHeaderTitle",
  "lines": 1,
  "barWidth": "181px",
  "barHeight": 20,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlayHeaderMeta: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayHeaderMeta",
  "lines": {
    "0": 2,
    "253": 1
  },
  "barWidth": {
    "0": [
      "199px",
      "50px"
    ],
    "253": "253px"
  },
  "barHeight": 12,
  "lineHeight": 1.35,
  "responsiveBy": "container"
};

export const forceOverlaySummary01Label: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlaySummary01Label",
  "lines": 1,
  "barWidth": "37px",
  "barHeight": 12,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlaySummary01Value: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlaySummary01Value",
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 34,
  "lineHeight": 1,
  "responsiveBy": "container"
};

export const forceOverlaySummary02Label: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlaySummary02Label",
  "lines": 1,
  "barWidth": "37px",
  "barHeight": 12,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlaySummary02Value: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlaySummary02Value",
  "lines": 1,
  "barWidth": "44px",
  "barHeight": 34,
  "lineHeight": 1,
  "responsiveBy": "container"
};

export const forceOverlaySummary03Label: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlaySummary03Label",
  "lines": 1,
  "barWidth": "32px",
  "barHeight": 12,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlaySummary03Value: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlaySummary03Value",
  "lines": 1,
  "barWidth": "38px",
  "barHeight": 34,
  "lineHeight": 1,
  "responsiveBy": "container"
};

export const forceOverlayTimeline01Title: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayTimeline01Title",
  "lines": {
    "0": 2,
    "255": 1
  },
  "barWidth": {
    "0": [
      "119px",
      "133px"
    ],
    "255": "255px"
  },
  "barHeight": 13,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlayTimeline01Detail: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayTimeline01Detail",
  "lines": {
    "0": 6,
    "155": 5,
    "177": 4,
    "224": 3,
    "639": 1,
    "338.812": 2
  },
  "barWidth": {
    "0": [
      "81px",
      "135px",
      "117px",
      "119px",
      "134px",
      "39px"
    ],
    "155": [
      "155px",
      "127px",
      "96px",
      "128px",
      "122px"
    ],
    "177": [
      "155px",
      "127px",
      "172px",
      "177px"
    ],
    "224": [
      "218px",
      "224px",
      "191px"
    ],
    "639": "639px",
    "338.812": [
      "338px",
      "298px"
    ]
  },
  "barHeight": 12,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlayTimeline02Title: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayTimeline02Title",
  "lines": {
    "0": 2,
    "244": 1
  },
  "barWidth": {
    "0": [
      "132px",
      "109px"
    ],
    "244": "244px"
  },
  "barHeight": 13,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlayTimeline02Detail: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayTimeline02Detail",
  "lines": {
    "0": 6,
    "142": 5,
    "172": 4,
    "227": 3,
    "624": 1,
    "310.968": 2
  },
  "barWidth": {
    "0": [
      "136px",
      "96px",
      "117px",
      "122px",
      "114px",
      "25px"
    ],
    "142": [
      "136px",
      "96px",
      "117px",
      "122px",
      "142px"
    ],
    "172": [
      "136px",
      "172px",
      "165px",
      "142px"
    ],
    "227": [
      "189px",
      "202px",
      "226px"
    ],
    "624": "623px",
    "310.968": [
      "310px",
      "310px"
    ]
  },
  "barHeight": 12,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlayTimeline03Title: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayTimeline03Title",
  "lines": {
    "0": 2,
    "263": 1
  },
  "barWidth": {
    "0": [
      "129px",
      "131px"
    ],
    "263": "263px"
  },
  "barHeight": 13,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const forceOverlayTimeline03Detail: GeneratedSkeletonTextEntry = {
  "textId": "forceOverlayTimeline03Detail",
  "lines": {
    "0": 5,
    "162": 4,
    "216": 3,
    "301": 2,
    "602": 1
  },
  "barWidth": {
    "0": [
      "121px",
      "134px",
      "103px",
      "109px",
      "122px"
    ],
    "162": [
      "161px",
      "151px",
      "158px",
      "122px"
    ],
    "216": [
      "216px",
      "184px",
      "196px"
    ],
    "301": [
      "300px",
      "298px"
    ],
    "602": "601px"
  },
  "barHeight": 12,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const skeletonForceOverlaySkeletonText: GeneratedSkeletonTextModule = {
  forceOverlayHeaderTitle,
  forceOverlayHeaderMeta,
  forceOverlaySummary01Label,
  forceOverlaySummary01Value,
  forceOverlaySummary02Label,
  forceOverlaySummary02Value,
  forceOverlaySummary03Label,
  forceOverlaySummary03Value,
  forceOverlayTimeline01Title,
  forceOverlayTimeline01Detail,
  forceOverlayTimeline02Title,
  forceOverlayTimeline02Detail,
  forceOverlayTimeline03Title,
  forceOverlayTimeline03Detail,
};
