/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const masonryLazyItem01Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "45px",
  "barHeight": 11.84,
  "lineHeight": 1.5
};

export const masonryLazyItem01Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "768": 2,
    "846": 1
  },
  "barWidth": {
    "0": "207px",
    "768": [
      "165px",
      "39px"
    ],
    "846": "207px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.5
};

export const masonryLazyItem01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "331": 3,
    "460": 2,
    "720": 3,
    "768": 5,
    "805": 4,
    "884": 3,
    "1140": 4,
    "1167": 3
  },
  "barWidth": {
    "0": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "331": [
      "219px",
      "225px",
      "210px"
    ],
    "460": [
      "304px",
      "354px"
    ],
    "720": [
      "241px",
      "268px",
      "145px"
    ],
    "768": [
      "160px",
      "140px",
      "139px",
      "161px",
      "46px"
    ],
    "805": [
      "160px",
      "140px",
      "187px",
      "163px"
    ],
    "884": [
      "219px",
      "225px",
      "210px"
    ],
    "1140": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "1167": [
      "219px",
      "225px",
      "210px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryLazyItem02Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "42px",
  "barHeight": 11.84,
  "lineHeight": 1.5
};

export const masonryLazyItem02Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "768": 2,
    "815": 1
  },
  "barWidth": {
    "0": "192px",
    "768": [
      "132px",
      "57px"
    ],
    "815": "192px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.5
};

export const masonryLazyItem02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "394": 2,
    "685": 1,
    "720": 3,
    "730": 2,
    "768": 5,
    "774": 4,
    "832": 3,
    "1014": 2,
    "1140": 3
  },
  "barWidth": {
    "0": [
      "174px",
      "200px",
      "193px"
    ],
    "394": [
      "283px",
      "288px"
    ],
    "685": "575px",
    "720": [
      "283px",
      "206px",
      "77px"
    ],
    "730": [
      "283px",
      "288px"
    ],
    "768": [
      "89px",
      "139px",
      "162px",
      "91px",
      "77px"
    ],
    "774": [
      "89px",
      "139px",
      "162px",
      "172px"
    ],
    "832": [
      "174px",
      "200px",
      "193px"
    ],
    "1014": [
      "283px",
      "288px"
    ],
    "1140": [
      "174px",
      "200px",
      "193px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryLazyItem03Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "45px",
  "barHeight": 11.84,
  "lineHeight": 1.5
};

export const masonryLazyItem03Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "154px",
  "barHeight": 16.32,
  "lineHeight": 1.5
};

export const masonryLazyItem03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "372": 2,
    "630": 1,
    "720": 2,
    "768": 4,
    "824": 3,
    "969": 2,
    "1140": 3,
    "1290": 2
  },
  "barWidth": {
    "0": [
      "196px",
      "180px",
      "138px"
    ],
    "372": [
      "266px",
      "253px"
    ],
    "630": "523px",
    "720": [
      "266px",
      "253px"
    ],
    "768": [
      "128px",
      "134px",
      "154px",
      "94px"
    ],
    "824": [
      "196px",
      "180px",
      "138px"
    ],
    "969": [
      "266px",
      "253px"
    ],
    "1140": [
      "196px",
      "180px",
      "138px"
    ],
    "1290": [
      "266px",
      "253px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryLazyItem04Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "38px",
  "barHeight": 11.84,
  "lineHeight": 1.5
};

export const masonryLazyItem04Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "768": 2,
    "800": 1
  },
  "barWidth": {
    "0": "185px",
    "768": [
      "110px",
      "71px"
    ],
    "800": "185px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.5
};

export const masonryLazyItem04Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "401": 2,
    "691": 1,
    "720": 3,
    "744": 2,
    "768": 4,
    "827": 3,
    "1028": 2,
    "1140": 3
  },
  "barWidth": {
    "0": [
      "198px",
      "193px",
      "182px"
    ],
    "401": [
      "282px",
      "295px"
    ],
    "691": "581px",
    "720": [
      "282px",
      "230px",
      "61px"
    ],
    "744": [
      "282px",
      "295px"
    ],
    "768": [
      "164px",
      "161px",
      "157px",
      "86px"
    ],
    "827": [
      "198px",
      "193px",
      "182px"
    ],
    "1028": [
      "282px",
      "295px"
    ],
    "1140": [
      "214px",
      "176px",
      "182px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryLazyItem05Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "28px",
  "barHeight": 11.84,
  "lineHeight": 1.5
};

export const masonryLazyItem05Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "768": 2,
    "800": 1
  },
  "barWidth": {
    "0": "185px",
    "768": [
      "142px",
      "39px"
    ],
    "800": "185px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.5
};

export const masonryLazyItem05Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "362": 3,
    "454": 2,
    "720": 3,
    "768": 5,
    "777": 4,
    "947": 3,
    "1134": 2,
    "1140": 4,
    "1258": 3
  },
  "barWidth": {
    "0": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "362": [
      "255px",
      "176px",
      "216px"
    ],
    "454": [
      "348px",
      "303px"
    ],
    "720": [
      "255px",
      "257px",
      "135px"
    ],
    "768": [
      "153px",
      "98px",
      "88px",
      "164px",
      "135px"
    ],
    "777": [
      "174px",
      "170px",
      "164px",
      "135px"
    ],
    "947": [
      "255px",
      "176px",
      "216px"
    ],
    "1134": [
      "348px",
      "303px"
    ],
    "1140": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "1258": [
      "255px",
      "176px",
      "216px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryLazyItem06Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "50px",
  "barHeight": 11.84,
  "lineHeight": 1.5
};

export const masonryLazyItem06Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "335": 1,
    "768": 2,
    "891": 1,
    "1140": 2,
    "1177": 1
  },
  "barWidth": {
    "0": [
      "138px",
      "87px"
    ],
    "335": "228px",
    "768": [
      "138px",
      "87px"
    ],
    "891": "228px",
    "1140": [
      "138px",
      "87px"
    ],
    "1177": "228px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.5
};

export const masonryLazyItem06Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "409": 2,
    "694": 1,
    "720": 3,
    "759": 2,
    "768": 5,
    "818": 4,
    "839": 3,
    "1043": 2,
    "1140": 3
  },
  "barWidth": {
    "0": [
      "195px",
      "177px",
      "203px"
    ],
    "409": [
      "277px",
      "302px"
    ],
    "694": "583px",
    "720": [
      "277px",
      "242px",
      "56px"
    ],
    "759": [
      "277px",
      "302px"
    ],
    "768": [
      "115px",
      "158px",
      "95px",
      "143px",
      "56px"
    ],
    "818": [
      "115px",
      "193px",
      "160px",
      "103px"
    ],
    "839": [
      "195px",
      "177px",
      "203px"
    ],
    "1043": [
      "277px",
      "302px"
    ],
    "1140": [
      "195px",
      "177px",
      "203px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryLazyLoadSkeletonText: GeneratedSkeletonTextModule = {
  masonryLazyItem01Badge,
  masonryLazyItem01Title,
  masonryLazyItem01Body,
  masonryLazyItem02Badge,
  masonryLazyItem02Title,
  masonryLazyItem02Body,
  masonryLazyItem03Badge,
  masonryLazyItem03Title,
  masonryLazyItem03Body,
  masonryLazyItem04Badge,
  masonryLazyItem04Title,
  masonryLazyItem04Body,
  masonryLazyItem05Badge,
  masonryLazyItem05Title,
  masonryLazyItem05Body,
  masonryLazyItem06Badge,
  masonryLazyItem06Title,
  masonryLazyItem06Body,
};
