/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const gridLazyLoadItem01Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px"
};

export const gridLazyLoadItem01Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "528": 2,
    "532": 1,
    "767": 2,
    "768": 1,
    "811": 2,
    "814": 1,
    "1062": 2,
    "1067": 1,
    "1300": 2,
    "1307": 1
  },
  "barWidth": {
    "0": "222px",
    "528": [
      "176px",
      "41px"
    ],
    "532": "222px",
    "767": [
      "176px",
      "41px"
    ],
    "768": "222px",
    "811": [
      "176px",
      "41px"
    ],
    "814": "222px",
    "1062": [
      "176px",
      "41px"
    ],
    "1067": "222px",
    "1300": [
      "176px",
      "41px"
    ],
    "1307": "222px"
  }
};

export const gridLazyLoadItem01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "430": 2,
    "528": 4,
    "538": 3,
    "767": 4,
    "768": 2,
    "811": 4,
    "821": 3,
    "1062": 4,
    "1077": 3,
    "1300": 4,
    "1320": 3
  },
  "barWidth": {
    "0": [
      "241px",
      "203px",
      "210px"
    ],
    "430": [
      "304px",
      "354px"
    ],
    "528": [
      "219px",
      "207px",
      "178px",
      "46px"
    ],
    "538": [
      "219px",
      "225px",
      "210px"
    ],
    "767": [
      "219px",
      "207px",
      "178px",
      "46px"
    ],
    "768": [
      "358px",
      "300px"
    ],
    "811": [
      "219px",
      "207px",
      "178px",
      "46px"
    ],
    "821": [
      "219px",
      "225px",
      "210px"
    ],
    "1062": [
      "219px",
      "207px",
      "178px",
      "46px"
    ],
    "1077": [
      "219px",
      "225px",
      "210px"
    ],
    "1300": [
      "219px",
      "207px",
      "178px",
      "46px"
    ],
    "1320": [
      "219px",
      "225px",
      "210px"
    ]
  }
};

export const gridLazyLoadItem02Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "43px"
};

export const gridLazyLoadItem02Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "205px"
};

export const gridLazyLoadItem02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "364": 2,
    "528": 3,
    "667": 2,
    "767": 3,
    "768": 2,
    "811": 3,
    "959": 2,
    "1062": 3,
    "1266": 2,
    "1300": 3
  },
  "barWidth": {
    "0": [
      "232px",
      "183px",
      "151px"
    ],
    "364": [
      "283px",
      "288px"
    ],
    "528": [
      "174px",
      "200px",
      "193px"
    ],
    "667": [
      "283px",
      "288px"
    ],
    "767": [
      "174px",
      "200px",
      "193px"
    ],
    "768": [
      "399px",
      "172px"
    ],
    "811": [
      "174px",
      "200px",
      "193px"
    ],
    "959": [
      "283px",
      "288px"
    ],
    "1062": [
      "174px",
      "200px",
      "193px"
    ],
    "1266": [
      "283px",
      "288px"
    ],
    "1300": [
      "174px",
      "200px",
      "193px"
    ]
  }
};

export const gridLazyLoadItem03Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px"
};

export const gridLazyLoadItem03Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "166px"
};

export const gridLazyLoadItem03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "342": 2,
    "528": 3,
    "621": 2,
    "767": 3,
    "768": 2,
    "811": 3,
    "912": 2,
    "1062": 3,
    "1200": 2,
    "1300": 3
  },
  "barWidth": {
    "0": [
      "229px",
      "228px",
      "57px"
    ],
    "342": [
      "266px",
      "253px"
    ],
    "528": [
      "196px",
      "180px",
      "138px"
    ],
    "621": [
      "266px",
      "253px"
    ],
    "767": [
      "196px",
      "180px",
      "138px"
    ],
    "768": [
      "380px",
      "138px"
    ],
    "811": [
      "196px",
      "180px",
      "138px"
    ],
    "912": [
      "266px",
      "253px"
    ],
    "1062": [
      "196px",
      "180px",
      "138px"
    ],
    "1200": [
      "266px",
      "253px"
    ],
    "1300": [
      "196px",
      "180px",
      "138px"
    ]
  }
};

export const gridLazyLoadItem04Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "39px"
};

export const gridLazyLoadItem04Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "198px"
};

export const gridLazyLoadItem04Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "371": 2,
    "528": 3,
    "682": 2,
    "767": 3,
    "768": 2,
    "811": 3,
    "973": 2,
    "1062": 3,
    "1287": 2,
    "1300": 3
  },
  "barWidth": {
    "0": [
      "214px",
      "218px",
      "141px"
    ],
    "371": [
      "282px",
      "295px"
    ],
    "528": [
      "214px",
      "218px",
      "141px"
    ],
    "682": [
      "282px",
      "295px"
    ],
    "767": [
      "214px",
      "218px",
      "141px"
    ],
    "768": [
      "395px",
      "182px"
    ],
    "811": [
      "214px",
      "218px",
      "141px"
    ],
    "973": [
      "282px",
      "295px"
    ],
    "1062": [
      "214px",
      "218px",
      "141px"
    ],
    "1287": [
      "282px",
      "295px"
    ],
    "1300": [
      "214px",
      "218px",
      "141px"
    ]
  }
};

export const gridLazyLoadItem05Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "29px"
};

export const gridLazyLoadItem05Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "198px"
};

export const gridLazyLoadItem05Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "332": 3,
    "424": 2,
    "528": 4,
    "599": 3,
    "767": 4,
    "768": 2,
    "811": 4,
    "884": 3,
    "1062": 4,
    "1168": 3,
    "1300": 4
  },
  "barWidth": {
    "0": [
      "174px",
      "170px",
      "239px",
      "61px"
    ],
    "332": [
      "255px",
      "176px",
      "216px"
    ],
    "424": [
      "348px",
      "303px"
    ],
    "528": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "599": [
      "255px",
      "176px",
      "216px"
    ],
    "767": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "768": [
      "348px",
      "303px"
    ],
    "811": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "884": [
      "255px",
      "176px",
      "216px"
    ],
    "1062": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "1168": [
      "255px",
      "176px",
      "216px"
    ],
    "1300": [
      "174px",
      "170px",
      "208px",
      "91px"
    ]
  }
};

export const gridLazyLoadItem06Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "51px"
};

export const gridLazyLoadItem06Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 1,
    "528": 2,
    "575": 1,
    "767": 2,
    "768": 1,
    "811": 2,
    "859": 1,
    "1062": 2,
    "1132": 1,
    "1300": 2
  },
  "barWidth": {
    "0": "243px",
    "528": [
      "146px",
      "93px"
    ],
    "575": "243px",
    "767": [
      "146px",
      "93px"
    ],
    "768": "243px",
    "811": [
      "146px",
      "93px"
    ],
    "859": "243px",
    "1062": [
      "146px",
      "93px"
    ],
    "1132": "243px",
    "1300": [
      "146px",
      "93px"
    ]
  }
};

export const gridLazyLoadItem06Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "379": 2,
    "528": 3,
    "697": 2,
    "767": 3,
    "768": 2,
    "811": 3,
    "988": 2,
    "1062": 3
  },
  "barWidth": {
    "0": [
      "221px",
      "151px",
      "203px"
    ],
    "379": [
      "277px",
      "302px"
    ],
    "528": [
      "195px",
      "177px",
      "203px"
    ],
    "697": [
      "277px",
      "302px"
    ],
    "767": [
      "195px",
      "177px",
      "203px"
    ],
    "768": [
      "376px",
      "203px"
    ],
    "811": [
      "195px",
      "177px",
      "203px"
    ],
    "988": [
      "277px",
      "302px"
    ],
    "1062": [
      "195px",
      "177px",
      "203px"
    ]
  }
};

export const gridLazyLoadItem07Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "45px"
};

export const gridLazyLoadItem07Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "217px"
};

export const gridLazyLoadItem07Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "421": 2,
    "528": 3,
    "768": 2,
    "811": 3
  },
  "barWidth": {
    "0": [
      "225px",
      "241px",
      "137px"
    ],
    "421": [
      "263px",
      "344px"
    ],
    "528": [
      "204px",
      "199px",
      "200px"
    ],
    "768": [
      "408px",
      "200px"
    ],
    "811": [
      "204px",
      "199px",
      "200px"
    ]
  }
};

export const gridLazyLoadItem08Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "56px"
};

export const gridLazyLoadItem08Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "326": 1,
    "528": 2,
    "587": 1,
    "767": 2,
    "768": 1,
    "811": 2,
    "872": 1,
    "1062": 2,
    "1150": 1,
    "1300": 2
  },
  "barWidth": {
    "0": [
      "154px",
      "92px"
    ],
    "326": "249px",
    "528": [
      "154px",
      "92px"
    ],
    "587": "249px",
    "767": [
      "154px",
      "92px"
    ],
    "768": "249px",
    "811": [
      "154px",
      "92px"
    ],
    "872": "249px",
    "1062": [
      "154px",
      "92px"
    ],
    "1150": "249px",
    "1300": [
      "154px",
      "92px"
    ]
  }
};

export const gridLazyLoadItem08Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "392": 2,
    "528": 3,
    "725": 2,
    "767": 3,
    "768": 2,
    "811": 3,
    "1016": 2,
    "1062": 3
  },
  "barWidth": {
    "0": [
      "211px",
      "237px",
      "168px"
    ],
    "392": [
      "316px",
      "304px"
    ],
    "528": [
      "211px",
      "219px",
      "185px"
    ],
    "725": [
      "316px",
      "304px"
    ],
    "767": [
      "211px",
      "219px",
      "185px"
    ],
    "768": [
      "362px",
      "258px"
    ],
    "811": [
      "211px",
      "219px",
      "185px"
    ],
    "1016": [
      "316px",
      "304px"
    ],
    "1062": [
      "211px",
      "219px",
      "185px"
    ]
  }
};

export const gridLazyLoadSkeletonText: GeneratedSkeletonTextModule = {
  gridLazyLoadItem01Badge,
  gridLazyLoadItem01Title,
  gridLazyLoadItem01Body,
  gridLazyLoadItem02Badge,
  gridLazyLoadItem02Title,
  gridLazyLoadItem02Body,
  gridLazyLoadItem03Badge,
  gridLazyLoadItem03Title,
  gridLazyLoadItem03Body,
  gridLazyLoadItem04Badge,
  gridLazyLoadItem04Title,
  gridLazyLoadItem04Body,
  gridLazyLoadItem05Badge,
  gridLazyLoadItem05Title,
  gridLazyLoadItem05Body,
  gridLazyLoadItem06Badge,
  gridLazyLoadItem06Title,
  gridLazyLoadItem06Body,
  gridLazyLoadItem07Badge,
  gridLazyLoadItem07Title,
  gridLazyLoadItem07Body,
  gridLazyLoadItem08Badge,
  gridLazyLoadItem08Title,
  gridLazyLoadItem08Body,
};
