/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const masonryBalancedItem01Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "45px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonryBalancedItem01Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "321": 1,
    "768": 2,
    "860": 1
  },
  "barWidth": {
    "0": [
      "50px",
      "49px",
      "65px",
      "40px"
    ],
    "321": "215px",
    "768": [
      "172px",
      "40px"
    ],
    "860": "215px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonryBalancedItem01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 10,
    "321": 4,
    "329": 3,
    "458": 2,
    "576": 4,
    "577": 2,
    "704": 3,
    "705": 2,
    "720": 3,
    "768": 5,
    "801": 4,
    "879": 3,
    "1140": 4,
    "1161": 3
  },
  "barWidth": {
    "0": [
      "85px",
      "71px",
      "76px",
      "59px",
      "50px",
      "86px",
      "61px",
      "44px",
      "47px",
      "46px"
    ],
    "321": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "329": [
      "219px",
      "225px",
      "210px"
    ],
    "458": [
      "304px",
      "354px"
    ],
    "576": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "577": [
      "448px",
      "210px"
    ],
    "704": [
      "241px",
      "268px",
      "145px"
    ],
    "705": [
      "561px",
      "97px"
    ],
    "720": [
      "241px",
      "268px",
      "145px"
    ],
    "768": [
      "160px",
      "140px",
      "139px",
      "161px",
      "46px"
    ],
    "801": [
      "160px",
      "140px",
      "187px",
      "163px"
    ],
    "879": [
      "219px",
      "225px",
      "210px"
    ],
    "1140": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "1161": [
      "219px",
      "225px",
      "210px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryBalancedItem02Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "42px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonryBalancedItem02Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "321": 1,
    "768": 2,
    "826": 1
  },
  "barWidth": {
    "0": [
      "85px",
      "49px",
      "58px"
    ],
    "321": "199px",
    "768": [
      "137px",
      "58px"
    ],
    "826": "199px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonryBalancedItem02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 9,
    "321": 3,
    "392": 2,
    "576": 3,
    "577": 2,
    "683": 1,
    "704": 3,
    "705": 1,
    "720": 3,
    "725": 2,
    "768": 5,
    "770": 4,
    "828": 3,
    "1010": 2,
    "1140": 3
  },
  "barWidth": {
    "0": [
      "31px",
      "53px",
      "81px",
      "54px",
      "74px",
      "84px",
      "17px",
      "70px",
      "77px"
    ],
    "321": [
      "174px",
      "200px",
      "193px"
    ],
    "392": [
      "283px",
      "288px"
    ],
    "576": [
      "174px",
      "200px",
      "193px"
    ],
    "577": [
      "420px",
      "151px"
    ],
    "683": "575px",
    "704": [
      "232px",
      "257px",
      "77px"
    ],
    "705": "575px",
    "720": [
      "283px",
      "206px",
      "77px"
    ],
    "725": [
      "283px",
      "288px"
    ],
    "768": [
      "89px",
      "139px",
      "162px",
      "91px",
      "77px"
    ],
    "770": [
      "89px",
      "139px",
      "162px",
      "172px"
    ],
    "828": [
      "174px",
      "200px",
      "193px"
    ],
    "1010": [
      "283px",
      "288px"
    ],
    "1140": [
      "174px",
      "200px",
      "193px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryBalancedItem03Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "45px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonryBalancedItem03Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "321": 1
  },
  "barWidth": {
    "0": [
      "75px",
      "82px"
    ],
    "321": "161px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonryBalancedItem03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 7,
    "321": 3,
    "370": 2,
    "576": 3,
    "577": 2,
    "628": 1,
    "704": 2,
    "705": 1,
    "720": 2,
    "768": 4,
    "820": 3,
    "965": 2,
    "1140": 3,
    "1284": 2
  },
  "barWidth": {
    "0": [
      "13px",
      "94px",
      "81px",
      "65px",
      "89px",
      "61px",
      "94px"
    ],
    "321": [
      "196px",
      "180px",
      "138px"
    ],
    "370": [
      "266px",
      "253px"
    ],
    "576": [
      "196px",
      "180px",
      "138px"
    ],
    "577": [
      "461px",
      "57px"
    ],
    "628": "523px",
    "704": [
      "266px",
      "253px"
    ],
    "705": "523px",
    "720": [
      "266px",
      "253px"
    ],
    "768": [
      "128px",
      "134px",
      "154px",
      "94px"
    ],
    "820": [
      "196px",
      "180px",
      "138px"
    ],
    "965": [
      "266px",
      "253px"
    ],
    "1140": [
      "196px",
      "180px",
      "138px"
    ],
    "1284": [
      "266px",
      "253px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryBalancedItem04Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "38px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonryBalancedItem04Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "321": 1,
    "768": 2,
    "811": 1
  },
  "barWidth": {
    "0": [
      "81px",
      "30px",
      "74px"
    ],
    "321": "192px",
    "768": [
      "115px",
      "74px"
    ],
    "811": "192px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonryBalancedItem04Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 10,
    "321": 3,
    "399": 2,
    "576": 3,
    "577": 2,
    "689": 1,
    "704": 3,
    "705": 1,
    "720": 3,
    "740": 2,
    "768": 4,
    "823": 3,
    "1024": 2,
    "1140": 3
  },
  "barWidth": {
    "0": [
      "67px",
      "26px",
      "62px",
      "46px",
      "64px",
      "43px",
      "62px",
      "75px",
      "38px",
      "61px"
    ],
    "321": [
      "214px",
      "176px",
      "182px"
    ],
    "399": [
      "282px",
      "295px"
    ],
    "576": [
      "214px",
      "176px",
      "182px"
    ],
    "577": [
      "436px",
      "141px"
    ],
    "689": "581px",
    "704": [
      "257px",
      "255px",
      "61px"
    ],
    "705": "581px",
    "720": [
      "282px",
      "230px",
      "61px"
    ],
    "740": [
      "282px",
      "295px"
    ],
    "768": [
      "164px",
      "161px",
      "157px",
      "86px"
    ],
    "823": [
      "198px",
      "193px",
      "182px"
    ],
    "1024": [
      "282px",
      "295px"
    ],
    "1140": [
      "214px",
      "218px",
      "141px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryBalancedItem05Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "28px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonryBalancedItem05Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "321": 1,
    "768": 2,
    "812": 1
  },
  "barWidth": {
    "0": [
      "51px",
      "94px",
      "40px"
    ],
    "321": "192px",
    "768": [
      "148px",
      "40px"
    ],
    "812": "192px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonryBalancedItem05Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 9,
    "321": 4,
    "360": 3,
    "452": 2,
    "576": 4,
    "577": 2,
    "704": 3,
    "705": 2,
    "720": 3,
    "768": 5,
    "773": 4,
    "943": 3,
    "1130": 2,
    "1140": 4,
    "1252": 3
  },
  "barWidth": {
    "0": [
      "73px",
      "76px",
      "16px",
      "77px",
      "88px",
      "83px",
      "76px",
      "70px",
      "61px"
    ],
    "321": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "360": [
      "255px",
      "176px",
      "216px"
    ],
    "452": [
      "348px",
      "303px"
    ],
    "576": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "577": [
      "435px",
      "216px"
    ],
    "704": [
      "255px",
      "257px",
      "135px"
    ],
    "705": [
      "591px",
      "61px"
    ],
    "720": [
      "255px",
      "257px",
      "135px"
    ],
    "768": [
      "153px",
      "98px",
      "88px",
      "164px",
      "135px"
    ],
    "773": [
      "174px",
      "170px",
      "164px",
      "135px"
    ],
    "943": [
      "255px",
      "176px",
      "216px"
    ],
    "1130": [
      "348px",
      "303px"
    ],
    "1140": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "1252": [
      "255px",
      "176px",
      "216px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryBalancedItem06Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "50px",
  "barHeight": 11.84,
  "lineHeight": 1.4
};

export const masonryBalancedItem06Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "321": 2,
    "341": 1,
    "576": 2,
    "577": 1,
    "768": 2,
    "903": 1,
    "1140": 2,
    "1196": 1
  },
  "barWidth": {
    "0": [
      "90px",
      "48px",
      "90px"
    ],
    "321": [
      "142px",
      "90px"
    ],
    "341": "236px",
    "576": [
      "142px",
      "90px"
    ],
    "577": "236px",
    "768": [
      "142px",
      "90px"
    ],
    "903": "236px",
    "1140": [
      "142px",
      "90px"
    ],
    "1196": "236px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2
};

export const masonryBalancedItem06Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 7,
    "321": 3,
    "407": 2,
    "576": 3,
    "577": 2,
    "691": 1,
    "704": 3,
    "705": 1,
    "720": 3,
    "755": 2,
    "768": 5,
    "814": 4,
    "834": 3,
    "1039": 2,
    "1140": 3
  },
  "barWidth": {
    "0": [
      "95px",
      "96px",
      "78px",
      "95px",
      "96px",
      "42px",
      "56px"
    ],
    "321": [
      "195px",
      "177px",
      "203px"
    ],
    "407": [
      "277px",
      "302px"
    ],
    "576": [
      "195px",
      "177px",
      "203px"
    ],
    "577": [
      "376px",
      "203px"
    ],
    "691": "583px",
    "704": [
      "277px",
      "242px",
      "56px"
    ],
    "705": "583px",
    "720": [
      "277px",
      "242px",
      "56px"
    ],
    "755": [
      "277px",
      "302px"
    ],
    "768": [
      "115px",
      "158px",
      "95px",
      "143px",
      "56px"
    ],
    "814": [
      "115px",
      "193px",
      "160px",
      "103px"
    ],
    "834": [
      "195px",
      "177px",
      "203px"
    ],
    "1039": [
      "277px",
      "302px"
    ],
    "1140": [
      "195px",
      "177px",
      "203px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55
};

export const masonryBalancedSkeletonText: GeneratedSkeletonTextModule = {
  masonryBalancedItem01Badge,
  masonryBalancedItem01Title,
  masonryBalancedItem01Body,
  masonryBalancedItem02Badge,
  masonryBalancedItem02Title,
  masonryBalancedItem02Body,
  masonryBalancedItem03Badge,
  masonryBalancedItem03Title,
  masonryBalancedItem03Body,
  masonryBalancedItem04Badge,
  masonryBalancedItem04Title,
  masonryBalancedItem04Body,
  masonryBalancedItem05Badge,
  masonryBalancedItem05Title,
  masonryBalancedItem05Body,
  masonryBalancedItem06Badge,
  masonryBalancedItem06Title,
  masonryBalancedItem06Body,
};
