/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const gridMinColumnWidthItem01Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "41px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem01Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "221.734": 1
  },
  "barWidth": {
    "0": [
      "176px",
      "41px"
    ],
    "221.734": "222px"
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "225": 3,
    "354": 2,
    "358": 2,
    "240.921": 3,
    "250.656": 3,
    "268.171": 3,
    "304.484": 3,
    "430.5": 2,
    "447.781": 2
  },
  "barWidth": {
    "0": [
      "219px",
      "207px",
      "178px",
      "46px"
    ],
    "225": [
      "219px",
      "225px",
      "210px"
    ],
    "354": [
      "304px",
      "354px"
    ],
    "358": [
      "358px",
      "300px"
    ],
    "240.921": [
      "241px",
      "203px",
      "210px"
    ],
    "250.656": [
      "241px",
      "251px",
      "163px"
    ],
    "268.171": [
      "241px",
      "268px",
      "145px"
    ],
    "304.484": [
      "304px",
      "304px",
      "46px"
    ],
    "430.5": [
      "430px",
      "228px"
    ],
    "447.781": [
      "448px",
      "210px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem02Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "38px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem02Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "205px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "288": 2,
    "311": 2,
    "379": 2,
    "399": 2,
    "220.75": 3,
    "232.281": 3,
    "257.328": 3,
    "283.046": 3,
    "328.484": 2,
    "419.937": 2
  },
  "barWidth": {
    "0": [
      "174px",
      "200px",
      "193px"
    ],
    "288": [
      "283px",
      "288px"
    ],
    "311": [
      "311px",
      "260px"
    ],
    "379": [
      "378px",
      "193px"
    ],
    "399": [
      "399px",
      "172px"
    ],
    "220.75": [
      "174px",
      "221px",
      "172px"
    ],
    "232.281": [
      "232px",
      "183px",
      "151px"
    ],
    "257.328": [
      "232px",
      "257px",
      "77px"
    ],
    "283.046": [
      "283px",
      "206px",
      "77px"
    ],
    "328.484": [
      "328px",
      "243px"
    ],
    "419.937": [
      "420px",
      "151px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem03Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "41px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem03Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "166px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "224": 3,
    "359": 2,
    "381": 2,
    "228.921": 3,
    "265.765": 2,
    "310.734": 2,
    "424.75": 2
  },
  "barWidth": {
    "0": [
      "196px",
      "180px",
      "138px"
    ],
    "224": [
      "196px",
      "224px",
      "94px"
    ],
    "359": [
      "359px",
      "160px"
    ],
    "381": [
      "380px",
      "138px"
    ],
    "228.921": [
      "229px",
      "228px",
      "57px"
    ],
    "265.765": [
      "266px",
      "253px"
    ],
    "310.734": [
      "311px",
      "208px"
    ],
    "424.75": [
      "424px",
      "94px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem04Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "35px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem04Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "198px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem04Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "295": 2,
    "395": 2,
    "437": 2,
    "255.5": 3,
    "256.656": 3,
    "282.093": 3,
    "329.453": 2
  },
  "barWidth": {
    "0": [
      "214px",
      "218px",
      "141px"
    ],
    "295": [
      "282px",
      "295px"
    ],
    "395": [
      "395px",
      "182px"
    ],
    "437": [
      "436px",
      "141px"
    ],
    "255.5": [
      "214px",
      "255px",
      "103px"
    ],
    "256.656": [
      "257px",
      "255px",
      "61px"
    ],
    "282.093": [
      "282px",
      "230px",
      "61px"
    ],
    "329.453": [
      "329px",
      "248px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem05Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "25px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem05Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "198px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem05Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "348": 2,
    "436": 2,
    "238.671": 4,
    "255.328": 3,
    "256.671": 3,
    "300.328": 3,
    "331.375": 3
  },
  "barWidth": {
    "0": [
      "174px",
      "170px",
      "208px",
      "91px"
    ],
    "348": [
      "348px",
      "303px"
    ],
    "436": [
      "435px",
      "216px"
    ],
    "238.671": [
      "174px",
      "170px",
      "239px",
      "61px"
    ],
    "255.328": [
      "255px",
      "176px",
      "216px"
    ],
    "256.671": [
      "255px",
      "257px",
      "135px"
    ],
    "300.328": [
      "255px",
      "300px",
      "91px"
    ],
    "331.375": [
      "255px",
      "331px",
      "61px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem06Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem06Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "243.328": 1
  },
  "barWidth": {
    "0": [
      "146px",
      "93px"
    ],
    "243.328": "243px"
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem06Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "268": 3,
    "313": 2,
    "343": 2,
    "376": 2,
    "220.75": 3,
    "251.328": 3,
    "277.125": 3,
    "302.25": 2
  },
  "barWidth": {
    "0": [
      "195px",
      "177px",
      "203px"
    ],
    "268": [
      "251px",
      "268px",
      "56px"
    ],
    "313": [
      "313px",
      "267px"
    ],
    "343": [
      "342px",
      "237px"
    ],
    "376": [
      "376px",
      "203px"
    ],
    "220.75": [
      "221px",
      "151px",
      "203px"
    ],
    "251.328": [
      "251px",
      "221px",
      "103px"
    ],
    "277.125": [
      "277px",
      "242px",
      "56px"
    ],
    "302.25": [
      "277px",
      "302px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem07Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "40px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem07Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "217px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem07Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "345": 2,
    "351": 2,
    "408": 2,
    "441": 2,
    "224.656": 3,
    "241.328": 3,
    "263.375": 3,
    "266.562": 3
  },
  "barWidth": {
    "0": [
      "204px",
      "199px",
      "200px"
    ],
    "345": [
      "263px",
      "344px"
    ],
    "351": [
      "350px",
      "257px"
    ],
    "408": [
      "408px",
      "200px"
    ],
    "441": [
      "440px",
      "167px"
    ],
    "224.656": [
      "225px",
      "212px",
      "167px"
    ],
    "241.328": [
      "225px",
      "241px",
      "137px"
    ],
    "263.375": [
      "263px",
      "236px",
      "104px"
    ],
    "266.562": [
      "263px",
      "267px",
      "73px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem08Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "50px",
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem08Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "249.328": 1
  },
  "barWidth": {
    "0": [
      "153px",
      "92px"
    ],
    "249.328": "249px"
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthItem08Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "316": 2,
    "363": 2,
    "417": 2,
    "435": 2,
    "236.609": 3,
    "313.125": 3
  },
  "barWidth": {
    "0": [
      "211px",
      "219px",
      "185px"
    ],
    "316": [
      "316px",
      "304px"
    ],
    "363": [
      "362px",
      "258px"
    ],
    "417": [
      "417px",
      "203px"
    ],
    "435": [
      "435px",
      "185px"
    ],
    "236.609": [
      "211px",
      "237px",
      "168px"
    ],
    "313.125": [
      "211px",
      "313px",
      "91px"
    ]
  },
  "responsiveBy": "container"
};

export const gridMinColumnWidthSkeletonText: GeneratedSkeletonTextModule = {
  gridMinColumnWidthItem01Badge,
  gridMinColumnWidthItem01Title,
  gridMinColumnWidthItem01Body,
  gridMinColumnWidthItem02Badge,
  gridMinColumnWidthItem02Title,
  gridMinColumnWidthItem02Body,
  gridMinColumnWidthItem03Badge,
  gridMinColumnWidthItem03Title,
  gridMinColumnWidthItem03Body,
  gridMinColumnWidthItem04Badge,
  gridMinColumnWidthItem04Title,
  gridMinColumnWidthItem04Body,
  gridMinColumnWidthItem05Badge,
  gridMinColumnWidthItem05Title,
  gridMinColumnWidthItem05Body,
  gridMinColumnWidthItem06Badge,
  gridMinColumnWidthItem06Title,
  gridMinColumnWidthItem06Body,
  gridMinColumnWidthItem07Badge,
  gridMinColumnWidthItem07Title,
  gridMinColumnWidthItem07Body,
  gridMinColumnWidthItem08Badge,
  gridMinColumnWidthItem08Title,
  gridMinColumnWidthItem08Body,
};
