import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/core.ts",
    "src/index.ts",
    "src/media.ts",
    "src/media-ready.ts",
    "src/responsive.ts",
    "src/reveal.ts",
    "src/slider.ts",
    "src/slider-ready.ts",
    "src/slider-arrows.ts",
    "src/slider-dots.ts",
    "src/slider-progress.ts",
    "src/slider-scrollbar.ts",
    "src/slider-ripple.ts",
    "src/slider-auto-play.ts",
    "src/slider-auto-scroll.ts",
    "src/slider-auto-height.ts",
    "src/slider-lazy-load.ts",
    "src/slider-parallax.ts",
    "src/slider-scale.ts",
    "src/slider-fade.ts",
    "src/slider-crossfade.ts",
    "src/slider-fullscreen.ts",
    "src/slider-loading.ts",
    "src/grid.ts",
    "src/grid-ready.ts",
    "src/grid-lazy-load.ts",
    "src/grid-fullscreen.ts",
    "src/grid-pagination.ts",
    "src/grid-load-more.ts",
    "src/grid-infinite-scroll.ts",
    "src/grid-virtualization.ts",
    "src/masonry.ts",
    "src/masonry-ready.ts",
    "src/masonry-fullscreen.ts",
    "src/masonry-lazy-load.ts",
    "src/masonry-text-wrap.ts",
    "src/masonry-pagination.ts",
    "src/masonry-load-more.ts",
    "src/masonry-infinite-scroll.ts",
    "src/masonry-virtualization.ts",
    "src/entries.ts",
    "src/entries-media-slider.ts",
    "src/entries-media-grid.ts",
    "src/entries-media-masonry.ts",
    "src/entries-ready.ts",
    "src/entries-pagination.ts",
    "src/entries-load-more.ts",
    "src/entries-infinite-scroll.ts",
    "src/entries-virtualization.ts",
    "src/rating-stars.ts",
    "src/skeleton-base.ts",
    "src/skeleton-cache.ts",
    "src/skeleton-cache-provider.ts",
    "src/skeleton-slider.ts",
    "src/skeleton-slider-restore.ts",
    "src/skeleton-grid.ts",
    "src/skeleton-masonry.ts",
    "src/fullscreen.ts",
    "src/fullscreen-slider.ts",
    "src/fullscreen-controls.ts",
    "src/fullscreen-captions.ts",
    "src/fullscreen-zoom-pan.ts",
    "src/fullscreen-video.ts",
    "src/fullscreen-lazy-load.ts",
    "src/fullscreen-crossfade.ts",
    "src/fullscreen-thumbnails.ts",
    "src/thumbnails.ts",
    "src/fullscreenThumbnails.ts",
    "src/video.ts",
    "src/zoomPan.ts",
    "src/zoomPan-hover.ts",
  ],
  format: ["esm"],
  loader: {
    ".css": "local-css",
  },
  splitting: true,
  treeshake: true,
  dts: true,
  sourcemap: false,
  clean: true,
  minify: true,
  metafile: true,
  external: ["react", "react-dom", "react/jsx-runtime"],
});
