/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const leadTrackTitle: GeneratedSkeletonTextEntry = {
  "textId": "leadTrackTitle",
  "lines": {
    "0": 2,
    "326": 1
  },
  "barWidth": {
    "0": [
      "172px",
      "40px"
    ],
    "326": "215px"
  }
};

export const leadTrackBody: GeneratedSkeletonTextEntry = {
  "textId": "leadTrackBody",
  "lines": {
    "0": 4,
    "340": 3,
    "472": 2,
    "1077": 1,
    "1200": 2
  },
  "barWidth": {
    "0": [
      "193px",
      "168px",
      "204px",
      "99px"
    ],
    "340": [
      "224px",
      "230px",
      "215px"
    ],
    "472": [
      "311px",
      "362px"
    ],
    "1077": "677px",
    "1200": [
      "366px",
      "307px"
    ]
  }
};

export const narrowRailTitle: GeneratedSkeletonTextEntry = {
  "textId": "narrowRailTitle",
  "lines": {
    "0": 1,
    "820": 2,
    "829": 1,
    "1200": 2,
    "1289": 1
  },
  "barWidth": {
    "0": "199px",
    "820": [
      "137px",
      "58px"
    ],
    "829": "199px",
    "1200": [
      "137px",
      "58px"
    ],
    "1289": "199px"
  }
};

export const narrowRailBody: GeneratedSkeletonTextEntry = {
  "textId": "narrowRailBody",
  "lines": {
    "0": 3,
    "405": 2,
    "702": 1,
    "768": 2,
    "820": 4,
    "835": 3,
    "936": 2,
    "1200": 5,
    "1235": 4,
    "1301": 3
  },
  "barWidth": {
    "0": [
      "178px",
      "205px",
      "197px"
    ],
    "405": [
      "289px",
      "294px"
    ],
    "702": "588px",
    "768": [
      "336px",
      "248px"
    ],
    "820": [
      "178px",
      "154px",
      "165px",
      "79px"
    ],
    "835": [
      "178px",
      "205px",
      "197px"
    ],
    "936": [
      "289px",
      "294px"
    ],
    "1200": [
      "91px",
      "142px",
      "145px",
      "114px",
      "79px"
    ],
    "1235": [
      "91px",
      "142px",
      "166px",
      "176px"
    ],
    "1301": [
      "178px",
      "205px",
      "197px"
    ]
  }
};

export const edgeSlotTitle: GeneratedSkeletonTextEntry = {
  "textId": "edgeSlotTitle",
  "lines": {
    "0": 1,
    "1200": 2
  },
  "barWidth": {
    "0": "161px",
    "1200": [
      "116px",
      "41px"
    ]
  }
};

export const edgeSlotBody: GeneratedSkeletonTextEntry = {
  "textId": "edgeSlotBody",
  "lines": {
    "0": 3,
    "382": 2,
    "646": 1,
    "768": 2,
    "820": 4,
    "953": 3,
    "1128": 2,
    "1200": 4
  },
  "barWidth": {
    "0": [
      "201px",
      "184px",
      "141px"
    ],
    "382": [
      "272px",
      "258px"
    ],
    "646": "534px",
    "768": [
      "367px",
      "163px"
    ],
    "820": [
      "130px",
      "183px",
      "150px",
      "59px"
    ],
    "953": [
      "201px",
      "184px",
      "141px"
    ],
    "1128": [
      "272px",
      "258px"
    ],
    "1200": [
      "130px",
      "137px",
      "113px",
      "141px"
    ]
  }
};

export const bridgeSpanTitle: GeneratedSkeletonTextEntry = {
  "textId": "bridgeSpanTitle",
  "lines": 1,
  "barWidth": "192px"
};

export const bridgeSpanBody: GeneratedSkeletonTextEntry = {
  "textId": "bridgeSpanBody",
  "lines": {
    "0": 3,
    "412": 2,
    "709": 1,
    "768": 2,
    "994": 1,
    "1200": 2
  },
  "barWidth": {
    "0": [
      "202px",
      "197px",
      "186px"
    ],
    "412": [
      "288px",
      "301px"
    ],
    "709": "594px",
    "768": [
      "336px",
      "253px"
    ],
    "994": "594px",
    "1200": [
      "336px",
      "253px"
    ]
  }
};

export const counterweightTitle: GeneratedSkeletonTextEntry = {
  "textId": "counterweightTitle",
  "lines": {
    "0": 1,
    "820": 2,
    "822": 1,
    "1200": 2,
    "1272": 1
  },
  "barWidth": {
    "0": "192px",
    "820": [
      "148px",
      "40px"
    ],
    "822": "192px",
    "1200": [
      "148px",
      "40px"
    ],
    "1272": "192px"
  }
};

export const counterweightBody: GeneratedSkeletonTextEntry = {
  "textId": "counterweightBody",
  "lines": {
    "0": 4,
    "371": 3,
    "466": 2,
    "820": 4,
    "893": 3,
    "1043": 2,
    "1200": 6,
    "1215": 5,
    "1238": 4
  },
  "barWidth": {
    "0": [
      "178px",
      "174px",
      "167px",
      "138px"
    ],
    "371": [
      "261px",
      "180px",
      "220px"
    ],
    "466": [
      "355px",
      "310px"
    ],
    "820": [
      "178px",
      "174px",
      "167px",
      "138px"
    ],
    "893": [
      "261px",
      "180px",
      "220px"
    ],
    "1043": [
      "355px",
      "310px"
    ],
    "1200": [
      "157px",
      "100px",
      "90px",
      "85px",
      "154px",
      "62px"
    ],
    "1215": [
      "157px",
      "100px",
      "90px",
      "167px",
      "138px"
    ],
    "1238": [
      "178px",
      "174px",
      "167px",
      "138px"
    ]
  }
};

export const finalRailTitle: GeneratedSkeletonTextEntry = {
  "textId": "finalRailTitle",
  "lines": {
    "0": 2,
    "347": 1,
    "820": 2,
    "1042": 1,
    "1200": 2
  },
  "barWidth": {
    "0": [
      "142px",
      "90px"
    ],
    "347": "236px",
    "820": [
      "142px",
      "90px"
    ],
    "1042": "236px",
    "1200": [
      "142px",
      "90px"
    ]
  }
};

export const finalRailBody: GeneratedSkeletonTextEntry = {
  "textId": "finalRailBody",
  "lines": {
    "0": 3,
    "419": 2,
    "711": 1,
    "768": 2,
    "820": 5,
    "945": 4,
    "971": 3,
    "1200": 5
  },
  "barWidth": {
    "0": [
      "199px",
      "181px",
      "208px"
    ],
    "419": [
      "283px",
      "309px"
    ],
    "711": "596px",
    "768": [
      "350px",
      "242px"
    ],
    "820": [
      "118px",
      "161px",
      "97px",
      "146px",
      "57px"
    ],
    "945": [
      "118px",
      "198px",
      "163px",
      "105px"
    ],
    "971": [
      "199px",
      "181px",
      "208px"
    ],
    "1200": [
      "118px",
      "135px",
      "123px",
      "99px",
      "105px"
    ]
  }
};

export const gridTemplateColumnsSkeletonText: GeneratedSkeletonTextModule = {
  leadTrackTitle,
  leadTrackBody,
  narrowRailTitle,
  narrowRailBody,
  edgeSlotTitle,
  edgeSlotBody,
  bridgeSpanTitle,
  bridgeSpanBody,
  counterweightTitle,
  counterweightBody,
  finalRailTitle,
  finalRailBody,
};
