/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const leadSpanTitle: GeneratedSkeletonTextEntry = {
  "textId": "leadSpanTitle",
  "lines": {
    "0": 2,
    "326": 1
  },
  "barWidth": {
    "0": [
      "172px",
      "40px"
    ],
    "326": "215px"
  }
};

export const leadSpanBody: GeneratedSkeletonTextEntry = {
  "textId": "leadSpanBody",
  "lines": {
    "0": 4,
    "340": 3,
    "472": 2,
    "1077": 1
  },
  "barWidth": {
    "0": [
      "193px",
      "168px",
      "204px",
      "99px"
    ],
    "340": [
      "224px",
      "230px",
      "215px"
    ],
    "472": [
      "311px",
      "362px"
    ],
    "1077": "677px"
  }
};

export const wideTileTitle: GeneratedSkeletonTextEntry = {
  "textId": "wideTileTitle",
  "lines": 1,
  "barWidth": "199px"
};

export const wideTileBody: GeneratedSkeletonTextEntry = {
  "textId": "wideTileBody",
  "lines": {
    "0": 3,
    "405": 2,
    "702": 1,
    "768": 2,
    "900": 3,
    "935": 2
  },
  "barWidth": {
    "0": [
      "178px",
      "205px",
      "197px"
    ],
    "405": [
      "289px",
      "294px"
    ],
    "702": "588px",
    "768": [
      "336px",
      "248px"
    ],
    "900": [
      "237px",
      "263px",
      "79px"
    ],
    "935": [
      "289px",
      "294px"
    ]
  }
};

export const tightTileTitle: GeneratedSkeletonTextEntry = {
  "textId": "tightTileTitle",
  "lines": 1,
  "barWidth": "161px"
};

export const tightTileBody: GeneratedSkeletonTextEntry = {
  "textId": "tightTileBody",
  "lines": {
    "0": 3,
    "382": 2,
    "646": 1,
    "768": 2,
    "900": 4,
    "944": 3,
    "1125": 2
  },
  "barWidth": {
    "0": [
      "201px",
      "184px",
      "141px"
    ],
    "382": [
      "272px",
      "258px"
    ],
    "646": "534px",
    "768": [
      "367px",
      "163px"
    ],
    "900": [
      "130px",
      "183px",
      "150px",
      "59px"
    ],
    "944": [
      "201px",
      "184px",
      "141px"
    ],
    "1125": [
      "272px",
      "258px"
    ]
  }
};

export const portraitOneTitle: GeneratedSkeletonTextEntry = {
  "textId": "portraitOneTitle",
  "lines": {
    "0": 1,
    "768": 2,
    "824": 1
  },
  "barWidth": {
    "0": "192px",
    "768": [
      "115px",
      "74px"
    ],
    "824": "192px"
  }
};

export const portraitOneBody: GeneratedSkeletonTextEntry = {
  "textId": "portraitOneBody",
  "lines": {
    "0": 3,
    "412": 2,
    "700": 3,
    "766": 2,
    "768": 5,
    "772": 4,
    "845": 3,
    "1049": 2,
    "1200": 3
  },
  "barWidth": {
    "0": [
      "202px",
      "197px",
      "186px"
    ],
    "412": [
      "288px",
      "301px"
    ],
    "700": [
      "262px",
      "261px",
      "62px"
    ],
    "766": [
      "288px",
      "301px"
    ],
    "768": [
      "100px",
      "158px",
      "137px",
      "119px",
      "62px"
    ],
    "772": [
      "167px",
      "165px",
      "161px",
      "88px"
    ],
    "845": [
      "202px",
      "197px",
      "186px"
    ],
    "1049": [
      "288px",
      "301px"
    ],
    "1200": [
      "219px",
      "223px",
      "144px"
    ]
  }
};

export const portraitTwoTitle: GeneratedSkeletonTextEntry = {
  "textId": "portraitTwoTitle",
  "lines": {
    "0": 1,
    "768": 2,
    "824": 1
  },
  "barWidth": {
    "0": "192px",
    "768": [
      "148px",
      "40px"
    ],
    "824": "192px"
  }
};

export const portraitTwoBody: GeneratedSkeletonTextEntry = {
  "textId": "portraitTwoBody",
  "lines": {
    "0": 4,
    "371": 3,
    "466": 2,
    "700": 3,
    "768": 6,
    "772": 5,
    "793": 4,
    "967": 3,
    "1163": 2,
    "1200": 4,
    "1287": 3
  },
  "barWidth": {
    "0": [
      "178px",
      "174px",
      "167px",
      "138px"
    ],
    "371": [
      "261px",
      "180px",
      "220px"
    ],
    "466": [
      "355px",
      "310px"
    ],
    "700": [
      "261px",
      "262px",
      "138px"
    ],
    "768": [
      "157px",
      "100px",
      "90px",
      "85px",
      "154px",
      "62px"
    ],
    "772": [
      "157px",
      "100px",
      "90px",
      "167px",
      "138px"
    ],
    "793": [
      "178px",
      "174px",
      "167px",
      "138px"
    ],
    "967": [
      "261px",
      "180px",
      "220px"
    ],
    "1163": [
      "355px",
      "310px"
    ],
    "1200": [
      "178px",
      "174px",
      "212px",
      "93px"
    ],
    "1287": [
      "261px",
      "180px",
      "220px"
    ]
  }
};

export const portraitThreeTitle: GeneratedSkeletonTextEntry = {
  "textId": "portraitThreeTitle",
  "lines": {
    "0": 2,
    "347": 1,
    "768": 2,
    "916": 1,
    "1200": 2,
    "1214": 1
  },
  "barWidth": {
    "0": [
      "142px",
      "90px"
    ],
    "347": "236px",
    "768": [
      "142px",
      "90px"
    ],
    "916": "236px",
    "1200": [
      "142px",
      "90px"
    ],
    "1214": "236px"
  }
};

export const portraitThreeBody: GeneratedSkeletonTextEntry = {
  "textId": "portraitThreeBody",
  "lines": {
    "0": 3,
    "419": 2,
    "700": 3,
    "768": 5,
    "835": 4,
    "856": 3,
    "1064": 2,
    "1200": 3
  },
  "barWidth": {
    "0": [
      "199px",
      "181px",
      "208px"
    ],
    "419": [
      "283px",
      "309px"
    ],
    "700": [
      "257px",
      "226px",
      "105px"
    ],
    "768": [
      "118px",
      "161px",
      "97px",
      "146px",
      "57px"
    ],
    "835": [
      "118px",
      "198px",
      "163px",
      "105px"
    ],
    "856": [
      "199px",
      "181px",
      "208px"
    ],
    "1064": [
      "283px",
      "309px"
    ],
    "1200": [
      "226px",
      "154px",
      "208px"
    ]
  }
};

export const narrowPortraitTitle: GeneratedSkeletonTextEntry = {
  "textId": "narrowPortraitTitle",
  "lines": {
    "0": 2,
    "375": 1,
    "768": 2,
    "973": 1,
    "1200": 2
  },
  "barWidth": {
    "0": [
      "182px",
      "78px"
    ],
    "375": "264px",
    "768": [
      "100px",
      "161px"
    ],
    "973": "264px",
    "1200": [
      "100px",
      "161px"
    ]
  }
};

export const narrowPortraitBody: GeneratedSkeletonTextEntry = {
  "textId": "narrowPortraitBody",
  "lines": {
    "0": 3,
    "462": 2,
    "700": 3,
    "768": 5,
    "792": 4,
    "858": 3,
    "1156": 2,
    "1200": 5,
    "1263": 4
  },
  "barWidth": {
    "0": [
      "209px",
      "204px",
      "204px"
    ],
    "462": [
      "269px",
      "352px"
    ],
    "700": [
      "269px",
      "241px",
      "106px"
    ],
    "768": [
      "134px",
      "131px",
      "143px",
      "125px",
      "75px"
    ],
    "792": [
      "168px",
      "97px",
      "177px",
      "171px"
    ],
    "858": [
      "209px",
      "204px",
      "204px"
    ],
    "1156": [
      "269px",
      "352px"
    ],
    "1200": [
      "134px",
      "131px",
      "143px",
      "125px",
      "75px"
    ],
    "1263": [
      "168px",
      "97px",
      "177px",
      "171px"
    ]
  }
};

export const closingPanoramaTitle: GeneratedSkeletonTextEntry = {
  "textId": "closingPanoramaTitle",
  "lines": {
    "0": 2,
    "353": 1,
    "768": 2,
    "928": 1
  },
  "barWidth": {
    "0": [
      "149px",
      "89px"
    ],
    "353": "242px",
    "768": [
      "149px",
      "89px"
    ],
    "928": "242px"
  }
};

export const closingPanoramaBody: GeneratedSkeletonTextEntry = {
  "textId": "closingPanoramaBody",
  "lines": {
    "0": 4,
    "326": 3,
    "433": 2,
    "700": 3,
    "768": 6,
    "769": 5,
    "780": 4,
    "873": 3,
    "1098": 2,
    "1268": 1
  },
  "barWidth": {
    "0": [
      "170px",
      "196px",
      "166px",
      "93px"
    ],
    "326": [
      "216px",
      "206px",
      "207px"
    ],
    "433": [
      "323px",
      "310px"
    ],
    "700": [
      "216px",
      "242px",
      "171px"
    ],
    "768": [
      "143px",
      "68px",
      "150px",
      "88px",
      "74px",
      "93px"
    ],
    "769": [
      "143px",
      "68px",
      "150px",
      "166px",
      "93px"
    ],
    "780": [
      "170px",
      "149px",
      "135px",
      "171px"
    ],
    "873": [
      "216px",
      "206px",
      "207px"
    ],
    "1098": [
      "323px",
      "310px"
    ],
    "1268": "637px"
  }
};

export const gridColumnsSkeletonText: GeneratedSkeletonTextModule = {
  leadSpanTitle,
  leadSpanBody,
  wideTileTitle,
  wideTileBody,
  tightTileTitle,
  tightTileBody,
  portraitOneTitle,
  portraitOneBody,
  portraitTwoTitle,
  portraitTwoBody,
  portraitThreeTitle,
  portraitThreeBody,
  narrowPortraitTitle,
  narrowPortraitBody,
  closingPanoramaTitle,
  closingPanoramaBody,
};
