/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const autoHeightOneKicker: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightOneKicker",
  "lines": 1,
  "barWidth": "85px",
  "barHeight": 12.16,
  "lineHeight": 1.2
};

export const autoHeightOneTitle: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightOneTitle",
  "lines": {
    "0": 2,
    "330": 1,
    "641": 1
  },
  "barWidth": {
    "0": [
      "142px",
      "56px"
    ],
    "330": "205px",
    "641": "205px"
  },
  "barHeight": {
    "0": 23.2,
    "330": 23.2,
    "641": 32
  },
  "lineHeight": 1.1
};

export const autoHeightOneCopy: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightOneCopy",
  "lines": {
    "0": 5,
    "323": 4,
    "386": 3,
    "489": 2,
    "641": 2,
    "768": 3,
    "786": 2
  },
  "barWidth": {
    "0": [
      "153px",
      "129px",
      "155px",
      "189px",
      "67px"
    ],
    "323": [
      "197px",
      "191px",
      "168px",
      "141px"
    ],
    "386": [
      "197px",
      "244px",
      "260px"
    ],
    "489": [
      "363px",
      "342px"
    ],
    "641": [
      "363px",
      "342px"
    ],
    "768": [
      "305px",
      "292px",
      "150px"
    ],
    "786": [
      "386px",
      "364px"
    ]
  },
  "barHeight": {
    "0": 15.04,
    "323": 15.04,
    "386": 15.04,
    "489": 15.04,
    "641": 16,
    "768": 16,
    "786": 16
  },
  "lineHeight": 1.45
};

export const autoHeightOneFooter: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightOneFooter",
  "lines": 1,
  "barWidth": "81px",
  "barHeight": 12.8,
  "lineHeight": 1.25
};

export const autoHeightTwoKicker: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightTwoKicker",
  "lines": 1,
  "barWidth": "65px",
  "barHeight": 12.16,
  "lineHeight": 1.2
};

export const autoHeightTwoTitle: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightTwoTitle",
  "lines": {
    "0": 2,
    "415": 1,
    "641": 1,
    "768": 2,
    "799": 1
  },
  "barWidth": {
    "0": [
      "152px",
      "131px"
    ],
    "415": "289px",
    "641": "289px",
    "768": [
      "210px",
      "180px"
    ],
    "799": "399px"
  },
  "barHeight": {
    "0": 23.2,
    "415": 23.2,
    "641": 32,
    "768": 32,
    "799": 32
  },
  "lineHeight": 1.1
};

export const autoHeightTwoCopy: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightTwoCopy",
  "lines": {
    "0": 6,
    "323": 5,
    "355": 4,
    "432": 3,
    "562": 2,
    "641": 2,
    "768": 3,
    "877": 2
  },
  "barWidth": {
    "0": [
      "153px",
      "129px",
      "155px",
      "189px",
      "182px",
      "47px"
    ],
    "323": [
      "197px",
      "191px",
      "168px",
      "154px",
      "148px"
    ],
    "355": [
      "197px",
      "221px",
      "230px",
      "215px"
    ],
    "432": [
      "286px",
      "274px",
      "307px"
    ],
    "562": [
      "445px",
      "426px"
    ],
    "641": [
      "445px",
      "426px"
    ],
    "768": [
      "305px",
      "292px",
      "326px"
    ],
    "877": [
      "474px",
      "454px"
    ]
  },
  "barHeight": {
    "0": 15.04,
    "323": 15.04,
    "355": 15.04,
    "432": 15.04,
    "562": 15.04,
    "641": 16,
    "768": 16,
    "877": 16
  },
  "lineHeight": 1.45
};

export const autoHeightTwoFooter: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightTwoFooter",
  "lines": 1,
  "barWidth": "52px",
  "barHeight": 12.8,
  "lineHeight": 1.25
};

export const autoHeightThreeKicker: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightThreeKicker",
  "lines": 1,
  "barWidth": "65px",
  "barHeight": 12.16,
  "lineHeight": 1.2
};

export const autoHeightThreeTitle: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightThreeTitle",
  "lines": {
    "0": 2,
    "417": 1,
    "641": 1,
    "768": 2,
    "803": 1
  },
  "barWidth": {
    "0": [
      "135px",
      "151px"
    ],
    "417": "292px",
    "641": "292px",
    "768": [
      "349px",
      "45px"
    ],
    "803": "402px"
  },
  "barHeight": {
    "0": 23.2,
    "417": 23.2,
    "641": 32,
    "768": 32,
    "803": 32
  },
  "lineHeight": 1.1
};

export const autoHeightThreeCopy: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightThreeCopy",
  "lines": {
    "0": 4,
    "356": 3,
    "462": 2,
    "641": 2
  },
  "barWidth": {
    "0": [
      "153px",
      "129px",
      "187px",
      "146px"
    ],
    "356": [
      "197px",
      "191px",
      "231px"
    ],
    "462": [
      "286px",
      "337px"
    ],
    "641": [
      "286px",
      "337px"
    ]
  },
  "barHeight": {
    "0": 15.04,
    "356": 15.04,
    "462": 15.04,
    "641": 16
  },
  "lineHeight": 1.45
};

export const autoHeightThreeFooter: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightThreeFooter",
  "lines": 1,
  "barWidth": "56px",
  "barHeight": 12.8,
  "lineHeight": 1.25
};

export const autoHeightFourKicker: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFourKicker",
  "lines": 1,
  "barWidth": "57px",
  "barHeight": 12.16,
  "lineHeight": 1.2
};

export const autoHeightFourTitle: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFourTitle",
  "lines": {
    "0": 2,
    "387": 1,
    "641": 1
  },
  "barWidth": {
    "0": [
      "177px",
      "78px"
    ],
    "387": "262px",
    "641": "262px"
  },
  "barHeight": {
    "0": 23.2,
    "387": 23.2,
    "641": 32
  },
  "lineHeight": 1.1
};

export const autoHeightFourCopy: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFourCopy",
  "lines": {
    "0": 7,
    "323": 6,
    "353": 5,
    "412": 4,
    "489": 3,
    "641": 3,
    "768": 4,
    "786": 3
  },
  "barWidth": {
    "0": [
      "153px",
      "129px",
      "155px",
      "189px",
      "182px",
      "168px",
      "55px"
    ],
    "323": [
      "197px",
      "191px",
      "168px",
      "154px",
      "162px",
      "163px"
    ],
    "353": [
      "197px",
      "221px",
      "212px",
      "182px",
      "227px"
    ],
    "412": [
      "286px",
      "274px",
      "256px",
      "227px"
    ],
    "489": [
      "363px",
      "356px",
      "329px"
    ],
    "641": [
      "363px",
      "356px",
      "329px"
    ],
    "768": [
      "305px",
      "292px",
      "341px",
      "173px"
    ],
    "786": [
      "386px",
      "379px",
      "350px"
    ]
  },
  "barHeight": {
    "0": 15.04,
    "323": 15.04,
    "353": 15.04,
    "412": 15.04,
    "489": 15.04,
    "641": 16,
    "768": 16,
    "786": 16
  },
  "lineHeight": 1.45
};

export const autoHeightFourFooter: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFourFooter",
  "lines": 1,
  "barWidth": "54px",
  "barHeight": 12.8,
  "lineHeight": 1.25
};

export const autoHeightFiveKicker: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFiveKicker",
  "lines": 1,
  "barWidth": "49px",
  "barHeight": 12.16,
  "lineHeight": 1.2
};

export const autoHeightFiveTitle: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFiveTitle",
  "lines": {
    "0": 2,
    "329": 1,
    "641": 1
  },
  "barWidth": {
    "0": [
      "128px",
      "70px"
    ],
    "329": "204px",
    "641": "204px"
  },
  "barHeight": {
    "0": 23.2,
    "329": 23.2,
    "641": 32
  },
  "lineHeight": 1.1
};

export const autoHeightFiveCopy: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFiveCopy",
  "lines": {
    "0": 3,
    "323": 2,
    "518": 1,
    "641": 1,
    "768": 2,
    "819": 1
  },
  "barWidth": {
    "0": [
      "153px",
      "129px",
      "102px"
    ],
    "323": [
      "197px",
      "191px"
    ],
    "518": "393px",
    "641": "393px",
    "768": [
      "305px",
      "108px"
    ],
    "819": "418px"
  },
  "barHeight": {
    "0": 15.04,
    "323": 15.04,
    "518": 15.04,
    "641": 16,
    "768": 16,
    "819": 16
  },
  "lineHeight": 1.45
};

export const autoHeightFiveFooter: GeneratedSkeletonTextEntry = {
  "textId": "autoHeightFiveFooter",
  "lines": 1,
  "barWidth": "43px",
  "barHeight": 12.8,
  "lineHeight": 1.25
};

export const sliderAutoHeightRowHeightCompensation: GeneratedSkeletonResponsiveNumber = {
  "0": 43.616,
  "330": 69.136,
  "353": 47.328,
  "386": 69.136,
  "387": 47.328,
  "415": 25.52,
  "417": 21.808,
  "641": 23.2,
  "768": 35.2,
  "786": 58.4,
  "799": 35.2,
  "803": 23.2
};

export const sliderAutoHeightSkeletonText: GeneratedSkeletonTextModule = {
  autoHeightOneKicker,
  autoHeightOneTitle,
  autoHeightOneCopy,
  autoHeightOneFooter,
  autoHeightTwoKicker,
  autoHeightTwoTitle,
  autoHeightTwoCopy,
  autoHeightTwoFooter,
  autoHeightThreeKicker,
  autoHeightThreeTitle,
  autoHeightThreeCopy,
  autoHeightThreeFooter,
  autoHeightFourKicker,
  autoHeightFourTitle,
  autoHeightFourCopy,
  autoHeightFourFooter,
  autoHeightFiveKicker,
  autoHeightFiveTitle,
  autoHeightFiveCopy,
  autoHeightFiveFooter,
};
