/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const masonryVideoHtml5Item01Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item01Title",
  "lines": {
    "0": 1,
    "820": 2,
    "853": 1
  },
  "barWidth": {
    "0": "211px",
    "820": [
      "168px",
      "40px"
    ],
    "853": "211px"
  },
  "barHeight": 16.64,
  "lineHeight": 1.5
};

export const masonryVideoHtml5Item01Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item01Body",
  "lines": {
    "0": 4,
    "327": 3,
    "456": 2,
    "820": 4,
    "881": 3,
    "1144": 2
  },
  "barWidth": {
    "0": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "327": [
      "219px",
      "225px",
      "210px"
    ],
    "456": [
      "304px",
      "354px"
    ],
    "820": [
      "189px",
      "165px",
      "151px",
      "145px"
    ],
    "881": [
      "219px",
      "225px",
      "210px"
    ],
    "1144": [
      "304px",
      "354px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.6
};

export const masonryVideoHtml5Item02Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item02Title",
  "lines": {
    "0": 1,
    "820": 2,
    "821": 1
  },
  "barWidth": {
    "0": "196px",
    "820": [
      "135px",
      "58px"
    ],
    "821": "196px"
  },
  "barHeight": 16.64,
  "lineHeight": 1.5
};

export const masonryVideoHtml5Item02Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item02Body",
  "lines": {
    "0": 3,
    "390": 2,
    "681": 1,
    "768": 2,
    "820": 4,
    "830": 3,
    "1012": 2
  },
  "barWidth": {
    "0": [
      "174px",
      "200px",
      "193px"
    ],
    "390": [
      "283px",
      "288px"
    ],
    "681": "575px",
    "768": [
      "378px",
      "193px"
    ],
    "820": [
      "174px",
      "150px",
      "161px",
      "77px"
    ],
    "830": [
      "174px",
      "200px",
      "193px"
    ],
    "1012": [
      "283px",
      "288px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.6
};

export const masonryVideoHtml5Item03Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item03Title",
  "lines": 1,
  "barWidth": "157px",
  "barHeight": 16.64,
  "lineHeight": 1.5
};

export const masonryVideoHtml5Item03Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item03Body",
  "lines": {
    "0": 3,
    "368": 2,
    "626": 1,
    "768": 2,
    "820": 4,
    "822": 3,
    "967": 2
  },
  "barWidth": {
    "0": [
      "196px",
      "180px",
      "138px"
    ],
    "368": [
      "266px",
      "253px"
    ],
    "626": "523px",
    "768": [
      "380px",
      "138px"
    ],
    "820": [
      "128px",
      "179px",
      "146px",
      "57px"
    ],
    "822": [
      "196px",
      "180px",
      "138px"
    ],
    "967": [
      "266px",
      "253px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.6
};

export const masonryVideoHtml5Item04Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item04Title",
  "lines": 1,
  "barWidth": "189px",
  "barHeight": 16.64,
  "lineHeight": 1.5
};

export const masonryVideoHtml5Item04Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item04Body",
  "lines": {
    "0": 3,
    "397": 2,
    "687": 1,
    "768": 2,
    "820": 4,
    "825": 3,
    "1026": 2
  },
  "barWidth": {
    "0": [
      "214px",
      "218px",
      "141px"
    ],
    "397": [
      "282px",
      "295px"
    ],
    "687": "581px",
    "768": [
      "329px",
      "248px"
    ],
    "820": [
      "164px",
      "161px",
      "183px",
      "61px"
    ],
    "825": [
      "198px",
      "193px",
      "182px"
    ],
    "1026": [
      "282px",
      "295px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.6
};

export const masonryVideoHtml5Item05Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item05Title",
  "lines": 1,
  "barWidth": "188px",
  "barHeight": 16.64,
  "lineHeight": 1.5
};

export const masonryVideoHtml5Item05Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item05Body",
  "lines": {
    "0": 3,
    "363": 2,
    "624": 1,
    "768": 2,
    "820": 3,
    "956": 2
  },
  "barWidth": {
    "0": [
      "174px",
      "170px",
      "168px"
    ],
    "363": [
      "255px",
      "261px"
    ],
    "624": "520px",
    "768": [
      "348px",
      "168px"
    ],
    "820": [
      "174px",
      "170px",
      "168px"
    ],
    "956": [
      "255px",
      "261px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.6
};

export const masonryVideoHtml5Item06Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item06Title",
  "lines": {
    "0": 2,
    "335": 1,
    "820": 2,
    "898": 1
  },
  "barWidth": {
    "0": [
      "140px",
      "89px"
    ],
    "335": "233px",
    "820": [
      "140px",
      "89px"
    ],
    "898": "233px"
  },
  "barHeight": 16.64,
  "lineHeight": 1.5
};

export const masonryVideoHtml5Item06Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryVideoHtml5Item06Body",
  "lines": {
    "0": 3,
    "409": 2,
    "694": 1,
    "768": 2,
    "820": 4,
    "837": 3,
    "1049": 2
  },
  "barWidth": {
    "0": [
      "195px",
      "181px",
      "203px"
    ],
    "409": [
      "277px",
      "306px"
    ],
    "694": "588px",
    "768": [
      "380px",
      "203px"
    ],
    "820": [
      "195px",
      "181px",
      "143px",
      "56px"
    ],
    "837": [
      "195px",
      "181px",
      "203px"
    ],
    "1049": [
      "277px",
      "306px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.6
};

export const masonryVideoHtml5SkeletonText: GeneratedSkeletonTextModule = {
  masonryVideoHtml5Item01Title,
  masonryVideoHtml5Item01Body,
  masonryVideoHtml5Item02Title,
  masonryVideoHtml5Item02Body,
  masonryVideoHtml5Item03Title,
  masonryVideoHtml5Item03Body,
  masonryVideoHtml5Item04Title,
  masonryVideoHtml5Item04Body,
  masonryVideoHtml5Item05Title,
  masonryVideoHtml5Item05Body,
  masonryVideoHtml5Item06Title,
  masonryVideoHtml5Item06Body,
};
