/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const gridVideoVimeoItem01Title: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem01Title",
  "lines": {
    "0": 2,
    "333": 1
  },
  "barWidth": {
    "0": [
      "177px",
      "42px"
    ],
    "333": "223px"
  }
};

export const gridVideoVimeoItem01Body: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem01Body",
  "lines": {
    "0": 4,
    "355": 3,
    "495": 2,
    "768": 3,
    "776": 2,
    "900": 4,
    "939": 3,
    "1222": 2
  },
  "barWidth": {
    "0": [
      "206px",
      "179px",
      "164px",
      "158px"
    ],
    "355": [
      "238px",
      "244px",
      "229px"
    ],
    "495": [
      "331px",
      "385px"
    ],
    "768": [
      "331px",
      "331px",
      "50px"
    ],
    "776": [
      "331px",
      "385px"
    ],
    "900": [
      "206px",
      "179px",
      "217px",
      "105px"
    ],
    "939": [
      "238px",
      "244px",
      "229px"
    ],
    "1222": [
      "331px",
      "385px"
    ]
  }
};

export const gridVideoVimeoItem02Title: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem02Title",
  "lines": 1,
  "barWidth": "206px"
};

export const gridVideoVimeoItem02Body: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem02Body",
  "lines": {
    "0": 4,
    "328": 3,
    "423": 2,
    "741": 1,
    "768": 2,
    "900": 3,
    "1078": 2
  },
  "barWidth": {
    "0": [
      "189px",
      "164px",
      "175px",
      "84px"
    ],
    "328": [
      "189px",
      "218px",
      "209px"
    ],
    "423": [
      "308px",
      "313px"
    ],
    "741": "625px",
    "768": [
      "357px",
      "264px"
    ],
    "900": [
      "189px",
      "218px",
      "209px"
    ],
    "1078": [
      "308px",
      "313px"
    ]
  }
};

export const gridVideoVimeoItem03Title: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem03Title",
  "lines": 1,
  "barWidth": "165px"
};

export const gridVideoVimeoItem03Body: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem03Body",
  "lines": {
    "0": 4,
    "324": 3,
    "399": 2,
    "682": 1,
    "768": 2,
    "900": 3,
    "1030": 2
  },
  "barWidth": {
    "0": [
      "139px",
      "194px",
      "159px",
      "62px"
    ],
    "324": [
      "213px",
      "196px",
      "150px"
    ],
    "399": [
      "289px",
      "275px"
    ],
    "682": "568px",
    "768": [
      "338px",
      "226px"
    ],
    "900": [
      "213px",
      "196px",
      "150px"
    ],
    "1030": [
      "289px",
      "275px"
    ]
  }
};

export const gridVideoVimeoItem04Title: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem04Title",
  "lines": 1,
  "barWidth": "199px"
};

export const gridVideoVimeoItem04Body: GeneratedSkeletonTextEntry = {
  "textId": "gridVideoVimeoItem04Body",
  "lines": {
    "0": 4,
    "326": 3,
    "431": 2,
    "748": 1,
    "768": 2,
    "900": 3,
    "1094": 2
  },
  "barWidth": {
    "0": [
      "178px",
      "175px",
      "199px",
      "66px"
    ],
    "326": [
      "215px",
      "210px",
      "198px"
    ],
    "431": [
      "307px",
      "321px"
    ],
    "748": "632px",
    "768": [
      "358px",
      "269px"
    ],
    "900": [
      "215px",
      "210px",
      "198px"
    ],
    "1094": [
      "307px",
      "321px"
    ]
  }
};

export const gridVideoVimeoSkeletonText: GeneratedSkeletonTextModule = {
  gridVideoVimeoItem01Title,
  gridVideoVimeoItem01Body,
  gridVideoVimeoItem02Title,
  gridVideoVimeoItem02Body,
  gridVideoVimeoItem03Title,
  gridVideoVimeoItem03Body,
  gridVideoVimeoItem04Title,
  gridVideoVimeoItem04Body,
};
