/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "viewport" | "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const responsiveTextHeaderTitle: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextHeaderTitle",
  "lines": {
    "0": 2,
    "274.562": 1
  },
  "barWidth": {
    "0": [
      "218px",
      "52px"
    ],
    "274.562": "274px"
  },
  "barHeight": 22,
  "lineHeight": 1.18,
  "responsiveBy": "container"
};

export const responsiveTextHeaderMeta: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextHeaderMeta",
  "lines": {
    "0": 2,
    "274": 1
  },
  "barWidth": {
    "0": [
      "216px",
      "55px"
    ],
    "274": "274px"
  },
  "barHeight": 13,
  "lineHeight": 1.35,
  "responsiveBy": "container"
};

export const responsiveTextItem01Label: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem01Label",
  "lines": 1,
  "barWidth": "34px",
  "barHeight": 11,
  "lineHeight": 1,
  "responsiveBy": "container"
};

export const responsiveTextItem01Title: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem01Title",
  "lines": {
    "0": 2,
    "241": 1
  },
  "barWidth": {
    "0": [
      "191px",
      "45px"
    ],
    "241": "240px"
  },
  "barHeight": 18,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const responsiveTextItem01Body: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem01Body",
  "lines": {
    "0": 3,
    "319.328": 2
  },
  "barWidth": {
    "0": [
      "198px",
      "203px",
      "189px"
    ],
    "319.328": [
      "275px",
      "319px"
    ]
  },
  "barHeight": 13,
  "lineHeight": 1.62,
  "responsiveBy": "container"
};

export const responsiveTextItem02Label: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem02Label",
  "lines": 1,
  "barWidth": "34px",
  "barHeight": 11,
  "lineHeight": 1,
  "responsiveBy": "container"
};

export const responsiveTextItem02Title: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem02Title",
  "lines": {
    "0": 2,
    "304.5": 1
  },
  "barWidth": {
    "0": [
      "142px",
      "158px"
    ],
    "304.5": "304px"
  },
  "barHeight": 18,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const responsiveTextItem02Body: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem02Body",
  "lines": {
    "0": 4,
    "321": 2,
    "224.968": 3
  },
  "barWidth": {
    "0": [
      "191px",
      "179px",
      "165px",
      "67px"
    ],
    "321": [
      "321px",
      "288px"
    ],
    "224.968": [
      "191px",
      "225px",
      "190px"
    ]
  },
  "barHeight": 13,
  "lineHeight": 1.62,
  "responsiveBy": "container"
};

export const responsiveTextItem03Label: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem03Label",
  "lines": 1,
  "barWidth": "29px",
  "barHeight": 11,
  "lineHeight": 1,
  "responsiveBy": "container"
};

export const responsiveTextItem03Title: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem03Title",
  "lines": {
    "0": 2,
    "305": 1
  },
  "barWidth": {
    "0": [
      "129px",
      "172px"
    ],
    "305": "304px"
  },
  "barHeight": 18,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const responsiveTextItem03Body: GeneratedSkeletonTextEntry = {
  "textId": "responsiveTextItem03Body",
  "lines": {
    "0": 4,
    "229": 3,
    "308": 2,
    "603": 1
  },
  "barWidth": {
    "0": [
      "142px",
      "163px",
      "162px",
      "126px"
    ],
    "229": [
      "142px",
      "226px",
      "229px"
    ],
    "308": [
      "308px",
      "292px"
    ],
    "603": "603px"
  },
  "barHeight": 13,
  "lineHeight": 1.62,
  "responsiveBy": "container"
};

export const skeletonResponsiveTextSkeletonText: GeneratedSkeletonTextModule = {
  responsiveTextHeaderTitle,
  responsiveTextHeaderMeta,
  responsiveTextItem01Label,
  responsiveTextItem01Title,
  responsiveTextItem01Body,
  responsiveTextItem02Label,
  responsiveTextItem02Title,
  responsiveTextItem02Body,
  responsiveTextItem03Label,
  responsiveTextItem03Title,
  responsiveTextItem03Body,
};
