/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "container";
type GeneratedSkeletonTextEntry = {
  textId?: string;
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const masonryRoundRobinItem01Badge: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem01Badge",
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem01Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem01Title",
  "lines": {
    "0": 2,
    "215.812": 1
  },
  "barWidth": {
    "0": [
      "172px",
      "40px"
    ],
    "215.812": "215px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem01Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem01Body",
  "lines": {
    "0": 5,
    "354": 2,
    "187.484": 4,
    "224.921": 3
  },
  "barWidth": {
    "0": [
      "160px",
      "140px",
      "139px",
      "161px",
      "46px"
    ],
    "354": [
      "304px",
      "354px"
    ],
    "187.484": [
      "160px",
      "140px",
      "187px",
      "163px"
    ],
    "224.921": [
      "219px",
      "225px",
      "210px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem02Badge: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem02Badge",
  "lines": 1,
  "barWidth": "43px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem02Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem02Title",
  "lines": {
    "0": 2,
    "199.484": 1
  },
  "barWidth": {
    "0": [
      "137px",
      "58px"
    ],
    "199.484": "199px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem02Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem02Body",
  "lines": {
    "0": 5,
    "288": 2,
    "172.609": 4,
    "200.453": 3,
    "575.687": 1
  },
  "barWidth": {
    "0": [
      "89px",
      "139px",
      "162px",
      "91px",
      "77px"
    ],
    "288": [
      "283px",
      "288px"
    ],
    "172.609": [
      "89px",
      "139px",
      "162px",
      "172px"
    ],
    "200.453": [
      "174px",
      "200px",
      "193px"
    ],
    "575.687": "575px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem03Badge: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem03Badge",
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem03Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem03Title",
  "lines": 1,
  "barWidth": "161px",
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem03Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem03Body",
  "lines": {
    "0": 4,
    "196.609": 3,
    "265.734": 2,
    "522.906": 1
  },
  "barWidth": {
    "0": [
      "128px",
      "134px",
      "154px",
      "94px"
    ],
    "196.609": [
      "196px",
      "180px",
      "138px"
    ],
    "265.734": [
      "266px",
      "253px"
    ],
    "522.906": "523px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem04Badge: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem04Badge",
  "lines": 1,
  "barWidth": "39px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem04Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem04Title",
  "lines": {
    "0": 2,
    "192.281": 1
  },
  "barWidth": {
    "0": [
      "115px",
      "74px"
    ],
    "192.281": "192px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem04Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem04Body",
  "lines": {
    "0": 4,
    "295": 2,
    "198.046": 3,
    "581.468": 1
  },
  "barWidth": {
    "0": [
      "164px",
      "161px",
      "157px",
      "86px"
    ],
    "295": [
      "282px",
      "295px"
    ],
    "198.046": [
      "198px",
      "193px",
      "182px"
    ],
    "581.468": "581px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem05Badge: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem05Badge",
  "lines": 1,
  "barWidth": "29px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem05Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem05Title",
  "lines": {
    "0": 2,
    "192.765": 1
  },
  "barWidth": {
    "0": [
      "148px",
      "40px"
    ],
    "192.765": "192px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem05Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem05Body",
  "lines": {
    "0": 5,
    "348": 2,
    "174.046": 4,
    "255.328": 3
  },
  "barWidth": {
    "0": [
      "153px",
      "98px",
      "89px",
      "164px",
      "135px"
    ],
    "348": [
      "348px",
      "303px"
    ],
    "174.046": [
      "174px",
      "170px",
      "164px",
      "135px"
    ],
    "255.328": [
      "255px",
      "176px",
      "216px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem06Badge: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem06Badge",
  "lines": 1,
  "barWidth": "51px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem06Title: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem06Title",
  "lines": {
    "0": 2,
    "236.453": 1
  },
  "barWidth": {
    "0": [
      "142px",
      "90px"
    ],
    "236.453": "236px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryRoundRobinItem06Body: GeneratedSkeletonTextEntry = {
  "textId": "masonryRoundRobinItem06Body",
  "lines": {
    "0": 5,
    "193.734": 4,
    "203.328": 3,
    "302.406": 2,
    "583.375": 1
  },
  "barWidth": {
    "0": [
      "115px",
      "158px",
      "95px",
      "143px",
      "56px"
    ],
    "193.734": [
      "115px",
      "193px",
      "160px",
      "103px"
    ],
    "203.328": [
      "195px",
      "177px",
      "203px"
    ],
    "302.406": [
      "277px",
      "302px"
    ],
    "583.375": "583px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryRoundRobinSkeletonText: GeneratedSkeletonTextModule = {
  masonryRoundRobinItem01Badge,
  masonryRoundRobinItem01Title,
  masonryRoundRobinItem01Body,
  masonryRoundRobinItem02Badge,
  masonryRoundRobinItem02Title,
  masonryRoundRobinItem02Body,
  masonryRoundRobinItem03Badge,
  masonryRoundRobinItem03Title,
  masonryRoundRobinItem03Body,
  masonryRoundRobinItem04Badge,
  masonryRoundRobinItem04Title,
  masonryRoundRobinItem04Body,
  masonryRoundRobinItem05Badge,
  masonryRoundRobinItem05Title,
  masonryRoundRobinItem05Body,
  masonryRoundRobinItem06Badge,
  masonryRoundRobinItem06Title,
  masonryRoundRobinItem06Body,
};
