import { dirname, resolve } from "node:path";
import type { BrowserSkeletonTextMeasurement } from "./browser";
import { SkeletonTextAnalyzerError } from "./types";

export type SkeletonTextGeneratedEntry = {
  exportName: string;
  value: {
    textId?: string;
    lines: number | Record<number, number>;
    barWidth?: string | string[] | Record<number, string | string[]>;
    lastBarWidth?: string | Record<number, string>;
    barHeight?: number | Record<number, number>;
    lineHeight?: number | Record<number, number>;
    responsiveBy?: "container";
  };
};

export type SkeletonTextGeneratedResponsiveNumberEntry = {
  exportName: string;
  value: number | Record<number, number>;
};

export type SkeletonTextGeneratedModule = {
  outputFile?: string;
  moduleExportName: string;
  entries: SkeletonTextGeneratedEntry[];
  responsiveNumberEntries: SkeletonTextGeneratedResponsiveNumberEntry[];
};

function formatTsValue(value: unknown, indentLevel = 0): string {
  const indent = "  ".repeat(indentLevel);
  const nextIndent = "  ".repeat(indentLevel + 1);

  if (
    value == null ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return JSON.stringify(value);
  }

  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  if (Array.isArray(value)) {
    if (!value.length) return "[]";
    return `[\n${value
      .map((entry) => `${nextIndent}${formatTsValue(entry, indentLevel + 1)}`)
      .join(",\n")}\n${indent}]`;
  }

  const entries = Object.entries(value);
  if (!entries.length) return "{}";

  return `{\n${entries
    .map(
      ([key, entryValue]) =>
        `${nextIndent}${JSON.stringify(key)}: ${formatTsValue(entryValue, indentLevel + 1)}`
    )
    .join(",\n")}\n${indent}}`;
}

export function buildGeneratedModuleFromBrowserMeasurements(args: {
  outputFile?: string;
  moduleExportName?: string;
  measurements: BrowserSkeletonTextMeasurement[];
}): SkeletonTextGeneratedModule {
  return {
    outputFile: args.outputFile,
    moduleExportName: args.moduleExportName?.trim() || "skeletonTextAuthoring",
    entries: args.measurements.flatMap((measurement) =>
      measurement.kind === "text"
        ? [
            {
              exportName: measurement.exportName,
              value: {
                ...(measurement.textId != null
                  ? { textId: measurement.textId }
                  : null),
                lines: measurement.value.lines,
                ...(measurement.value.barWidth != null
                  ? { barWidth: measurement.value.barWidth }
                  : null),
                ...(measurement.value.lastBarWidth != null
                  ? { lastBarWidth: measurement.value.lastBarWidth }
                  : null),
                ...(measurement.value.barHeight != null
                  ? { barHeight: measurement.value.barHeight }
                  : null),
                ...(measurement.value.lineHeight != null
                  ? { lineHeight: measurement.value.lineHeight }
                  : null),
                ...(measurement.value.responsiveBy != null
                  ? { responsiveBy: measurement.value.responsiveBy }
                  : null),
              },
            },
          ]
        : []
    ),
    responsiveNumberEntries: args.measurements.flatMap((measurement) =>
      measurement.kind === "responsiveNumber"
        ? [
            {
              exportName: measurement.exportName,
              value: measurement.value,
            },
          ]
        : []
    ),
  };
}

export function renderSkeletonTextGeneratedModule(
  generated: SkeletonTextGeneratedModule
): string {
  const lines: string[] = [
    "/* This file is autogenerated by generate_skeleton_text_module.ts. */",
    "/* eslint-disable */",
    "",
    "type GeneratedSkeletonTextLines = number | Record<number, number>;",
    "type GeneratedSkeletonTextBarWidth =",
    "  | string",
    "  | string[]",
    "  | Record<number, string | string[]>;",
    "type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;",
    "type GeneratedSkeletonTextBarHeight = number | Record<number, number>;",
    "type GeneratedSkeletonTextLineHeight = number | Record<number, number>;",
    'type GeneratedSkeletonTextResponsiveBy = "container";',
    "type GeneratedSkeletonTextEntry = {",
    "  textId?: string;",
    "  lines: GeneratedSkeletonTextLines;",
    "  barWidth?: GeneratedSkeletonTextBarWidth;",
    "  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;",
    "  barHeight?: GeneratedSkeletonTextBarHeight;",
    "  lineHeight?: GeneratedSkeletonTextLineHeight;",
    "  responsiveBy?: GeneratedSkeletonTextResponsiveBy;",
    "};",
    "type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;",
    "type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;",
    "",
  ];

  for (const entry of generated.entries) {
    lines.push(
      `export const ${entry.exportName}: GeneratedSkeletonTextEntry = ${formatTsValue(entry.value)};`,
      ""
    );
  }

  for (const entry of generated.responsiveNumberEntries) {
    lines.push(
      `export const ${entry.exportName}: GeneratedSkeletonResponsiveNumber = ${formatTsValue(entry.value)};`,
      ""
    );
  }

  lines.push(
    `export const ${generated.moduleExportName}: GeneratedSkeletonTextModule = {`
  );
  for (const entry of generated.entries) {
    lines.push(`  ${entry.exportName},`);
  }
  lines.push("};", "");

  return `${lines.join("\n")}`;
}

export function resolveGeneratedOutputFile(args: {
  manifestPath: string;
  outputFile?: string;
  outputPathOverride?: string;
}): string {
  const outputFile = args.outputPathOverride?.trim() || args.outputFile?.trim();

  if (!outputFile) {
    throw new SkeletonTextAnalyzerError(
      "INVALID_INPUT",
      "Generator output file must be provided via manifest.outputFile or --output.",
      { manifestPath: args.manifestPath }
    );
  }

  return resolve(dirname(args.manifestPath), outputFile);
}
