/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const cardOneTitle: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "324": 2,
    "500": 3,
    "592": 2,
    "768": 3,
    "877": 2
  },
  "barWidth": {
    "0": [
      "151px",
      "161px",
      "78px"
    ],
    "324": [
      "214px",
      "181px"
    ],
    "500": [
      "151px",
      "161px",
      "78px"
    ],
    "592": [
      "214px",
      "181px"
    ],
    "768": [
      "151px",
      "161px",
      "78px"
    ],
    "877": [
      "214px",
      "181px"
    ]
  }
};

export const cardOnePrice: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "35px"
};

export const cardTwoTitle: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "461": 1,
    "500": 3,
    "557": 2,
    "768": 3,
    "841": 2,
    "1156": 1,
    "1200": 2
  },
  "barWidth": {
    "0": [
      "151px",
      "196px"
    ],
    "461": "351px",
    "500": [
      "151px",
      "89px",
      "103px"
    ],
    "557": [
      "151px",
      "196px"
    ],
    "768": [
      "151px",
      "89px",
      "103px"
    ],
    "841": [
      "151px",
      "196px"
    ],
    "1156": "351px",
    "1200": [
      "151px",
      "196px"
    ]
  }
};

export const cardTwoPrice: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "28px"
};

export const cardThreeTitle: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "324": 2,
    "500": 3,
    "591": 2,
    "768": 3,
    "876": 2
  },
  "barWidth": {
    "0": [
      "133px",
      "196px",
      "69px"
    ],
    "324": [
      "213px",
      "188px"
    ],
    "500": [
      "133px",
      "157px",
      "108px"
    ],
    "591": [
      "213px",
      "188px"
    ],
    "768": [
      "133px",
      "157px",
      "108px"
    ],
    "876": [
      "213px",
      "188px"
    ]
  }
};

export const cardThreePrice: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "27px"
};

export const sliderCardsRowHeightCompensation: GeneratedSkeletonResponsiveNumber = {
  "0": 0,
  "324": 20.8,
  "338": 0,
  "592": 20.8,
  "621": 0,
  "768": 20.8,
  "772": 0,
  "877": 20.8,
  "906": 0
};

export const sliderCardsSkeletonText: GeneratedSkeletonTextModule = {
  cardOneTitle,
  cardOnePrice,
  cardTwoTitle,
  cardTwoPrice,
  cardThreeTitle,
  cardThreePrice,
};
