export const FULLSCREEN_THUMBNAIL_SLOT_Z_INDEX = 2;
export const FULLSCREEN_CLOSE_MEDIA_LAYER_Z_INDEX =
  FULLSCREEN_THUMBNAIL_SLOT_Z_INDEX + 1;
export const FULLSCREEN_SLIDER_CONTROLS_Z_INDEX =
  FULLSCREEN_CLOSE_MEDIA_LAYER_Z_INDEX + 1;
export const FULLSCREEN_INTRO_MEDIA_Z_INDEX_OFFSET = 10;
export const FULLSCREEN_MODAL_ROOT_Z_INDEX_OFFSET = 0;
export const FULLSCREEN_OVERLAY_PROMOTED_ROOT_Z_INDEX_OFFSET =
  FULLSCREEN_INTRO_MEDIA_Z_INDEX_OFFSET + 1;
export const FULLSCREEN_CLOSE_BODY_LAYER_Z_INDEX = 2147483600;
export const FULLSCREEN_TOP_CHROME_Z_INDEX = 2147483647;

export function resolveFullscreenRootZIndexOffset(
  promoteOverlaysAboveIntroMedia: boolean
) {
  return promoteOverlaysAboveIntroMedia
    ? FULLSCREEN_OVERLAY_PROMOTED_ROOT_Z_INDEX_OFFSET
    : FULLSCREEN_MODAL_ROOT_Z_INDEX_OFFSET;
}
