/* This file is autogenerated by generate_skeleton_text_module.ts. */
/* eslint-disable */

type GeneratedSkeletonTextLines = number | Record<number, number>;
type GeneratedSkeletonTextBarWidth =
  | string
  | string[]
  | Record<number, string | string[]>;
type GeneratedSkeletonTextLastBarWidth = string | Record<number, string>;
type GeneratedSkeletonTextBarHeight = number | Record<number, number>;
type GeneratedSkeletonTextLineHeight = number | Record<number, number>;
type GeneratedSkeletonTextResponsiveBy = "container";
type GeneratedSkeletonTextEntry = {
  lines: GeneratedSkeletonTextLines;
  barWidth?: GeneratedSkeletonTextBarWidth;
  lastBarWidth?: GeneratedSkeletonTextLastBarWidth;
  barHeight?: GeneratedSkeletonTextBarHeight;
  lineHeight?: GeneratedSkeletonTextLineHeight;
  responsiveBy?: GeneratedSkeletonTextResponsiveBy;
};
type GeneratedSkeletonResponsiveNumber = number | Record<number, number>;
type GeneratedSkeletonTextModule = Record<string, GeneratedSkeletonTextEntry>;

export const masonryHorizontalOrderItem01Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem01Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "215px",
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem01Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "225": 3,
    "354": 2,
    "663": 1
  },
  "barWidth": {
    "0": [
      "189px",
      "165px",
      "199px",
      "97px"
    ],
    "225": [
      "219px",
      "225px",
      "210px"
    ],
    "354": [
      "304px",
      "354px"
    ],
    "663": "662px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem02Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "43px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem02Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "199.484": 1
  },
  "barWidth": {
    "0": [
      "137px",
      "58px"
    ],
    "199.484": "199px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem02Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 5,
    "288": 2,
    "172.5": 4,
    "200.453": 3,
    "575.687": 1
  },
  "barWidth": {
    "0": [
      "89px",
      "139px",
      "142px",
      "111px",
      "77px"
    ],
    "288": [
      "283px",
      "288px"
    ],
    "172.5": [
      "89px",
      "139px",
      "162px",
      "172px"
    ],
    "200.453": [
      "174px",
      "200px",
      "193px"
    ],
    "575.687": "575px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem03Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "46px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem03Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "161": 1
  },
  "barWidth": {
    "0": [
      "116px",
      "41px"
    ],
    "161": "161px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem03Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 4,
    "196.25": 3,
    "265.734": 2,
    "522.906": 1
  },
  "barWidth": {
    "0": [
      "128px",
      "134px",
      "110px",
      "138px"
    ],
    "196.25": [
      "196px",
      "180px",
      "138px"
    ],
    "265.734": [
      "266px",
      "253px"
    ],
    "522.906": "523px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem04Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "39px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem04Title: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "192px",
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem04Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 3,
    "295": 2,
    "581.468": 1
  },
  "barWidth": {
    "0": [
      "214px",
      "176px",
      "182px"
    ],
    "295": [
      "282px",
      "295px"
    ],
    "581.468": "581px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem05Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "29px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem05Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "192.5": 1
  },
  "barWidth": {
    "0": [
      "148px",
      "40px"
    ],
    "192.5": "192px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem05Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 6,
    "164": 5,
    "348": 2,
    "173.75": 4,
    "255.64": 3
  },
  "barWidth": {
    "0": [
      "115px",
      "136px",
      "89px",
      "83px",
      "151px",
      "61px"
    ],
    "164": [
      "153px",
      "98px",
      "89px",
      "164px",
      "135px"
    ],
    "348": [
      "348px",
      "303px"
    ],
    "173.75": [
      "174px",
      "170px",
      "164px",
      "135px"
    ],
    "255.64": [
      "255px",
      "176px",
      "216px"
    ]
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem06Badge: GeneratedSkeletonTextEntry = {
  "lines": 1,
  "barWidth": "51px",
  "barHeight": 11.84,
  "lineHeight": 1.4,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem06Title: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 2,
    "236.453": 1
  },
  "barWidth": {
    "0": [
      "142px",
      "90px"
    ],
    "236.453": "236px"
  },
  "barHeight": 16.32,
  "lineHeight": 1.2,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderItem06Body: GeneratedSkeletonTextEntry = {
  "lines": {
    "0": 5,
    "193.5": 4,
    "203.328": 3,
    "302.406": 2,
    "583.375": 1
  },
  "barWidth": {
    "0": [
      "115px",
      "132px",
      "121px",
      "143px",
      "56px"
    ],
    "193.5": [
      "115px",
      "193px",
      "160px",
      "103px"
    ],
    "203.328": [
      "195px",
      "177px",
      "203px"
    ],
    "302.406": [
      "277px",
      "302px"
    ],
    "583.375": "583px"
  },
  "barHeight": 14.72,
  "lineHeight": 1.55,
  "responsiveBy": "container"
};

export const masonryHorizontalOrderSkeletonText: GeneratedSkeletonTextModule = {
  masonryHorizontalOrderItem01Badge,
  masonryHorizontalOrderItem01Title,
  masonryHorizontalOrderItem01Body,
  masonryHorizontalOrderItem02Badge,
  masonryHorizontalOrderItem02Title,
  masonryHorizontalOrderItem02Body,
  masonryHorizontalOrderItem03Badge,
  masonryHorizontalOrderItem03Title,
  masonryHorizontalOrderItem03Body,
  masonryHorizontalOrderItem04Badge,
  masonryHorizontalOrderItem04Title,
  masonryHorizontalOrderItem04Body,
  masonryHorizontalOrderItem05Badge,
  masonryHorizontalOrderItem05Title,
  masonryHorizontalOrderItem05Body,
  masonryHorizontalOrderItem06Badge,
  masonryHorizontalOrderItem06Title,
  masonryHorizontalOrderItem06Body,
};
